### ISSUE TITLE
Maximum entropy classifier: when will be added to natural?

### ISSUE THREAD

**Issue by cocodrino** [NaturalNode/natural#106]
any plan for add MEC to natural, I'm trying found a node or javascript lib than include it, thanks!!

**Comment by Hugo-ter-Doest** [comment]
I am working on a maximum entropy classifier in nodejs. It is still under development, but the scaling algorithm is implemented and working already. At the moment I am doing tests to make sure it works as expected. At some moment I will do a PR to add it to natural.

Feel free to take a look at 
https://github.com/Hugo-ter-Doest/MaxEnt

Regards,
Hugo
