### ISSUE TITLE
Naive Bayes getClassifications wrong sorting 

### ISSUE THREAD

**Issue by lucasllano** [NaturalNode/natural#113]
I trained the classifier with over 3000 documents, when I asked getClassifications I noticed values where not sorted so the first value was not the highest probability. I changed the sign to sort from lowest probability to largest and then retuned the last value. That did the trick. Here is the code:

function getClassifications(observation) {
    var classifier = this;
    var labels = [];

```
for(var className in this.classFeatures) {
labels.push({label: className,
      value: classifier.probabilityOfClass(observation, className)});
}

return labels.sort(function(x, y) {return y.value - x.value});
```

}

and instead of calling Classify I did the following:

 result = classifier.getClassifications(test[i]);
      response.push([test[i], result[result.length - 1].label])

**Comment by zenahirsch** [comment]
I trained a BayesClassifier with 2000 documents, then ran `classify()` on a new string. It returned: `'Tip Jar'`. However, when I display all the classified weights on the same string with `getClassifications()`, I get the following:

```json
[ { label: 'Tip Jar', value: 1.8626451492309635e-12 },
  { label: 'Enhancer + Music Store',
    value: 1.0485760000000035e-12 },
  { label: 'API', value: 2.0552924344690413e-19 },
  { label: 'Pre-Sales', value: 4.795682347094443e-20 },
  { label: 'General Features', value: 2.929687499999967e-21 },
  { label: 'Mobile + Device', value: 7.130728072141918e-22 },
  { label: 'Collections + Sharing', value: 9.019431321600049e-23 },
  { label: 'Conversion', value: 7.416645662212573e-24 },
  { label: 'Uploading', value: 4.4526961897789003e-26 },
  { label: 'Video Settings / Player',
    value: 5.228077340186636e-28 },
  { label: 'VOD', value: 2.949131387168577e-28 },
  { label: 'Trust & Safety', value: 4.013102485708889e-31 },
  { label: 'Billing', value: 6.931280135727475e-33 },
  { label: 'Account', value: 3.5034639398149423e-35 },
  { label: 'Other', value: 1.4290460825902654e-39 } ]
```

`Tip Jar` is not the classification with the highest value. Am I doing something wrong?
