### ISSUE TITLE
Jaro Winkler Distance not counting transpositions correctly

### ISSUE THREAD

**Issue by dnarkiewicz** [NaturalNode/natural#162]
/lib/natural/distance/jaro-winkler_distance.js

The first existence check in the for loop should be matching against i not k 

```
74    // count transpositions
75    var k = 0;
76
77    for(var i = 0; i < s1.length; i++) {
78      if(matches1[k]) {
```

should be

```
74    // count transpositions
75    var k = 0;
76
77    for(var i = 0; i < s1.length; i++) {
78      if(matches1[i]) {
```

**Comment by syzer** [comment]
+1
now it returns outside specified range:
[0,1]

ex:
-0.5095499738356881

**Comment by Hugo-ter-Doest** [comment]
Could you please give some examples so I can test this with the modified distance function?

Hugo

**Comment by syzer** [comment]
@Hugo-ter-Doest sorry.. that didnt post failing test...
now i don't remember test case.. 
will look in repos/histories and try to get back to you

**Comment by Hugo-ter-Doest** [comment]
I looked at the possibilities for a negative distance in the code, and I think this is not possible. The only possiblity would be that <code>m - t</code> is negative. See my comments in the second loop that looks for transpositions below with prefix HtD:
````javascript
    k = 0; // reset string 2 index
    for(i = 0; i < s1.length; i++) { // loop to find transpositions
        if (!matches1[i]) { // non-matching character
            continue;
        }
        while(!matches2[k]) { // move k index to the next match
            k++;
        }
        // HtD: i and k are at a match
        if (s1[i] !== s2[k]) { // if the characters don't match, increase transposition
          // HtD: t is always less than the number of matches m, because transpositions are a subset of matches
            t++;
        }
        k++; // iterate k index normally
    }

    // transpositions divided by 2
    t = t / 2.0;

    return ((m / s1.length) + (m / s2.length) + ((m - t) / m)) / 3.0; // HtD: therefore, m - t > 0, and m - t < m
    // HtD: => return value is between 0 and 1
````
Another possility for a negative outcome is in the main function:
```javascript
        // HtD: 1 - jaro >= 0
        return jaro + l * p * (1 - jaro);
```
But we already know that jaro is between 0 and 1. So, with the current implementation I think it is impossible to find negative distances.

Hugo
