### ISSUE TITLE
Dutch Stemming

### ISSUE THREAD

**Issue by martijndeb** [NaturalNode/natural#165]
Hi there,

First of all, I am not a language expert.
I try to implement a dutch Porter Stemmer, so I looked at the snowball implementation (http://snowball.tartarus.org/algorithms/dutch/stemmer.html) and the NLTK 3 DutchStemmer (http://www.nltk.org/_modules/nltk/stem/snowball.html#DutchStemmer).

Dutch is a language with lots of exceptions and is said to be hard to learn for foreigners. Hence I discovered that in the documentation of the snwball stemmer lots of words are wrongly stemmed (because of exceptions). Does this count for other languages as well?
Do I need to build extra rules to correct those words or are the snowball and NLTK implementations generally accepted?

Some examples (original word, proposed stem by snowball, correct stem):
ophaalt, ophaalt, ophaal
ophaalsystemen, ophaalsystem, ophaalsystemen,
opgrijnzen, opgrijnz, opgrijns,
opglimlachen, opglimlacht, opglimlach,
opgraven, opgrav, opgraaf (debatable)

Currently I am around half way of implementing the snowball version in Natural (without any extra rules). What decision was made for the other stemmers?

(the porterstemmer in progress; https://github.com/sexybiggetje/natural/blob/master/lib/natural/stemmers/porter_stemmer_nl.js)

**Comment by DavidBruant** [comment]
Why was this issue closed? I don't see the nl stemmer in the repo.
