### ISSUE TITLE
Question: Classifier neutral output

### ISSUE THREAD

**Issue by pablodenadai** [NaturalNode/natural#168]
Hi there, thanks for maintaining this project!

Given the following example:

```
var natural = require('natural'),
  classifier = new natural.BayesClassifier();

classifier.addDocument('i am foo', 'foo');
classifier.addDocument('he is foo', 'foo');
classifier.addDocument('i am bar', 'bar');
classifier.addDocument('she is bar', 'bar');

classifier.train();

console.log(classifier.classify('they are foo'));
// => 'foo'

console.log(classifier.classify('they are bar'));
// => 'bar'

console.log(classifier.classify('they are baz'));
// => 'foo'
```

Why does the last one return `foo`? Shouldn't it be "neutral"? (eg. `undefined` or `null`)

Thanks!

**Comment by roykolak** [comment]
Jumping in, I was surprised by this behavior also

**Comment by chrisumbel** [comment]
I'm having a hard time getting back involved, but am going to try to make time soon.

**Comment by chrisumbel** [comment]
NLTK returns 'foo', 'bar', 'foo' as well. Since it seems a case that's unlikely to occur with production sets returning identical results to NLTK is probably just going to have to be good enough. 

It is an interesting case, however, and if anybody can point to another approach that has precedent I'd be happy to look into it.

**Comment by brandonwillard** [comment]
Looks like the linear predictor is returning zero (i.e. no matches to any terms), so that the likelihoods it returns are 0.5 (the sigmoid at 0).  In this case, all terms are then equal and the max becomes meaningless.
This can happen when there's no intercept term.
