### ISSUE TITLE
Wordnet DB

### ISSUE THREAD

**Issue by yanickrochon** [NaturalNode/natural#170]
I was reading in the README that the Wordnet database is no longer downloaded automatically, and I also see that there are no dependencies to [WNdb](https://github.com/moos/WNdb).

Although, may I suggest my branch of [WNdb](https://github.com/yanickrochon/WNdb/tree/new-install)? As it is smaller and does not contain the Wordnet archive in the repository, but downloads them directly from Princeton's servers ?

**Comment by morungos** [comment]
I've independently had a similar issue, and did end up assembling a custom-ish WNdb, for several reasons. I needed the morphological exclusions, which aren't in WNdb, and are also not versioned the same as the main data files. (I personally needed WN3.0, because there's no synset mappings to 3.1 that could locate). So I also needed to make a fork, but I stuck close to the WNdb line. 

However, I ended up wanting more from the API than is exposed within natural, so I've started working on a more substantial implementation for a Wordnet interface specifically. I'm not especially convinced it needs to be, or should be, a core part of natural anyway. There's also a hideous performance problem in natural's Wordnet file reading which I've patched here: https://github.com/morungos/wordnet/commit/d4c91d0ec32e2ba87987dab7079b9758c85bfdf6. I also found that a promises interface was a good plan. There's still plenty I want to do on this (e.g., better error handling) but I'm happy for the work I'm doing to find it's way back into natural if that's helpful (since that's mostly where it came from). 

I am happy to assist if it's useful, either by sourcing occasional PRs or just being a source of development activity on node and Wordnet. I do have some of the testing you might want, and I've kept the API compatible so far.

**Comment by kkoch986** [comment]
@morungos i will probably reference your fix in the coming weeks as i process a rewrite of the natural WNdb code, would love to hear about extensions to the API that you had in mind so i can keep them in mind as I go through

Thanks!

**Comment by morungos** [comment]
Very happy to help. Probably the best reference would be the tests, which are fairly thorough. See: https://github.com/morungos/wordnet/blob/develop/test/wordnet_test.coffee. Some parts of the API are inspired by that of WordNet::QueryData in Perl for high-level access (i.e., a way to get from words to senses with offsets, in a way that's consistent with many WN data files, such as wn-domains (which I use). Although WN::QD is awful when it comes to getting all the data on a single sense, so I stuck with the current model for that. It's a bit of clunky hybrid for now. 

A late change was to add promises to most of the API, which I feel makes it much easier to use. Although Bluebird can promisify much of it, to date, the error handling isn't right for normal callbacks, so I'd need to work on this -- this goes back to the file system access code, which isn't quite as cautious as I'd like. I'll probably find time to make these changes over the weekend, and I'll probably do some work redesigning some of the API, to make the data from `get` a bit easier.

**Comment by kkoch986** [comment]
i like the idea of having something well tested and also offering a higher level API. I'm not sure we'll go the promises route just yet, just to avoid bringing in any more dependencies.

**Comment by yanickrochon** [comment]
If I may interrupt, Node 0.12 will come out in a near future, and `Promise` is a natively supported. Currently, a lot of projects run on 0.11 anyway, and do support promises, too.

As a requirement, it can just be stated that they need to shim a `Promise` implementation into the `global` object themselves if they run the stable 0.10 branch of Node.js.

Supporting the legacy callback system should not be considered for new modules as the community is moving away from it.

**Comment by morungos** [comment]
@yanickrochon caught me just as I was writing a reply, and I was going to concede promises and I probably shouldn't, although the priority is probably getting the callbacks to error properly. For my subset/extension of the WN code, I don't have the infrastructure of the rest of natural to worry about, so I can maybe do a better job of this than I have so far, fixing the callback error flags and probably making the callback optional, with promises returned when not passed. 

Natural has more to worry about than WN, with a much bigger community (including me!), and so promises is a bigger decision. Personally, in my code, I've found the asynchronous error handling of promises is so very much simpler and clearer that callbacks are miserably painful by comparison.

**Comment by kkoch986** [comment]
@morungos pretty much said it. I think from all the issues and comments around WN there are plenty of people actually using it so I'm not really inclined to start mixing up the APIs. I'm not opposed to starting to move towards promises and adding a higher level API but we've decided as a part of rewriting the wordnet module that it remains backwards compatible. I'll do some research and see if we can't have our cake and eat it too but for now the main goal is to repair the existing WN code and possibly add higher level functionality on top of that.

**Comment by kkoch986** [comment]
@yanickrochon on a side note, we're considering a plan to build a corpus manager / download utility and i think your WNdb fork would serve as a pretty solid basis for that. Did you have any interest in working on such a project and if not would you be ok with us using most of your install.js as the foundation of the natural corpus downloader?

**Comment by yanickrochon** [comment]
Yes, sure! You may take my fork as a foundation. Will this manager be part of this repository, or will it be it's own module?

**Comment by kkoch986** [comment]
Great thanks! the plan is for it to be part of the natural repository similar to how the corpus manager works in NLTK. initially it'll only support wordnet but we can expand it as we add in other corpus-based algorithms

**Comment by yanickrochon** [comment]
I'm monitoring this repository, so I will surely help in the matter. I have not tested my fork under Windows (I'm on Linux), so I cannot say of the progress bars (when downloading archives) work or not in this environment.

So, I guess the idea is to have a, for example, `bin/natural.js` file that will be added to a `bin` value inside the `package.json` file? (Also, this is now officially outside the scope of this issue :) )

**Comment by kkoch986** [comment]
you're totally right, see #211

**Comment by silentrob** [comment]
:+1:
