### ISSUE TITLE
Double Metaphone not processing several cases correctly

### ISSUE THREAD

**Issue by wooorm** [NaturalNode/natural#173]
A few cases (validated with [this online tool](http://swoodbridge.com/DoubleMetaPhone), and my own [library](https://github.com/wooorm/double-metaphone)):

- `"caesar"` should process to `["SSR", "SSR"]`, currently to `["KSR", "KSR"]`;
- `"ach"` should process to `["AK", "AK"]`, currently to `["AX", "AK"]`;
- `"chemical"` should process to `["KMKL", "KMKL"]`, currently to `["XMKL", "XMKL"]`;
- `"choral"` should process to `["KRL", "KRL"]`, currently to `["XRL", "XRL"]`;
- …and some more (I created 166 unit tests for my library, and natural fails on 20 of them);

P.S. Not trying to be a pain here, with all the issues I have with Natural :wink:

**Comment by chrisumbel** [comment]
Seems centered around the "C" processing.
