### ISSUE TITLE
Porter stemmer not stemming properly

### ISSUE THREAD

**Issue by wooorm** [NaturalNode/natural#176]
Out of 23532 input/outputs provided with the original algorithm, Natural fails on 558 cases (Natural@0.1.28).

Failures include:

- `ace` to `ac`;
- `acknowledg` to `acknowledg`;
- `adoptedly` to `adoptedli`;
- `aedile` to `aedil`;
- …

Source: See http://tartarus.org/martin/PorterStemmer/, and search for "To test the programs out".

**Comment by chrisumbel** [comment]
Didn't mean to close. I've handled the cases mentioned initially, but more remain. Will be addressing.

**Comment by pranavatgithub** [comment]
Still bugs with PorterStemmer.Anyone working on it??
please check the examples
1. natural.PorterStemmer.stem("recharged")  ---->> recharg 
2.natural.PorterStemmer.stem("subscribed") ----->> subscrib
3.natural.PorterStemmer.stem("restored") ------->>restor

**Comment by pranavatgithub** [comment]
i think below algorithm is working better.
URL : - -  http://takafumir.github.io/javascript-lemmatizer/html/lemmatizer_sample.html
git repo: -- https://github.com/takafumir/javascript-lemmatizer

**Comment by kkoch986** [comment]
assuming whats at the endo f those arrows is the output from natural i think those are correct. i verified with another unrelated implementation.
