### ISSUE TITLE
Browserify compatibility?

### ISSUE THREAD

**Issue by ahamid** [NaturalNode/natural#189]
Hello, natural looks like a great library and I am investigating using it in the browser, via Browserify.
I noticed a couple of things:

```
    $ gulp browserify
    module "WNdb" not found from "./node_modules/natural/lib/natural/wordnet/wordnet.js"
    ...
    module "lapack" not found from "./node_modules/natural/node_modules/sylvester/lib/node-sylvester/matrix.js"
```

`WNdb` module consists of a (large ~10mb) blob of data, while `lapack` which is a native library, is being pulled in by `sylvester`.

My understanding is that `WNdb` is optional in `natural` and `lapack` is optional in `sylvester` (it uses detection to fallback on pure JS routines).  It appears that the problem may be with Browserify attempting to eagerly retrieve these dynamic dependencies.  I will pursue a remedy within Browserify and log this issue in case I find a workaround, but I am wondering in parallel whether first class browser/Browserify will be a goal for natural.

**Comment by tsjeyasarathi** [comment]
I tried suggestions in #25 but in vain. browserify creates a library but fs dependencies causes issues. Can someone help with the client side version of natural with classifier ?

**Comment by dspdog** [comment]
here is a client side version with most of the exports ~400kb; can use with var natural = require('natural'); 

https://gist.github.com/dspdog/105faa58bd8493c81f0b51bcc6046555
