### ISSUE TITLE
fix(README.md): Classifiers invalid example

### ISSUE THREAD

**Issue by Nate-Wilkins** [NaturalNode/natural#210]
[README.md#classifiers](https://github.com/NaturalNode/natural#classifiers) for the 
`console.log(classifier.getClassifications('i am long copper'));` example reads as
```js
[ { label: 'sell', value: 0.39999999999999997 },
  { label: 'buy', value: 0.19999999999999998 } ]
```
when it should read as
```js
[ { label: 'buy', value: 0.39999999999999997 },
  { label: 'sell', value: 0.19999999999999998 } ]
```

And the `classifier.addDocument('buy the q''s', 'buy');` line needs escape sequences :+1:

**Comment by chrisumbel** [comment]
fixed, thanks for the report!
