### ISSUE TITLE
Installation dependency issue with conceptnet

### ISSUE THREAD

**Issue by arunbahl** [NaturalNode/natural#217]
I've been unable to install the conceptnet dependency, and a search on npmjs.com shows it as not found. 
https://www.npmjs.com/search?q=conceptnet
Was this supposed to be "concept-net" or am I doing something wrong?

**Comment by kkoch986** [comment]
concept net should not be a dependency of natural, see https://github.com/NaturalNode/natural/blob/master/package.json#L13-L21

Did you install natural VIA npm?

**Comment by arunbahl** [comment]
My apologies, this issue was meant for a different package (superscript)!

**Comment by kkoch986** [comment]
no problem!
