### ISSUE TITLE
Need to test token against lowercase for stopwords 

### ISSUE THREAD

**Issue by mikeh2** [NaturalNode/natural#218]
inside of stemmer.js there needs to be a test of the token.toLowerCase to the stopword (which is lowercase):

new Tokenizer().tokenize(text).forEach(function(token) {
           var test = token.toLowerCase();
           if(keepStops || stopwords.words.indexOf(test) == -1) {
               // now add the actual token
               stemmedTokens.push(stemmer.stem(token));
           }
        });

**Comment by kkoch986** [comment]
sorry to leave this one hanging, its a quick fix im just on the home stretch of what im currently working on. Would be glad to merge it in a PR otherwise i should have this out soon

**Comment by mamaral** [comment]
Just noticed this one now - I ***believe*** this was addressed in https://github.com/NaturalNode/natural/pull/235.

**Comment by kkoch986** [comment]
yes thanks for pointing that out!
