### ISSUE TITLE
Optimize module size from npm

### ISSUE THREAD

**Issue by jlescot** [NaturalNode/natural#219]
It seems that the module contains many files that increase a lot its size when doing a `npm install natural`.

Do you think it would make sense to release it excluding the `coverage` and `spec` folders (you could do that with a `.npmignore` file - https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) ?

![natural_size](https://cloud.githubusercontent.com/assets/2051333/6186703/4fa101f6-b37d-11e4-969f-b507f832ea76.png)

**Comment by kkoch986** [comment]
That would be good, coverage is not actually in the repo i guess it gets generated while running one of the npm scripts (test if i had to guess) I can definitely put together an npmignore file asap.

thanks!
