### ISSUE TITLE
Soundex - incorrect results

### ISSUE THREAD

**Issue by derrickpelletier** [NaturalNode/natural#221]
I'm getting a fair chunk of incorrect results from the soundex algorithm used in `natural`.
For example, names like `Lloyd` and `Pfister` aren't returning expected results.

I have my own soundex implementation [here](https://github.com/derrickpelletier/soundex-encode), and my results there match up with various sources online and with the MySQL implementation.

For example:
```
"Lloyd"
natural: "L430"
expected: "L300"
---------
"Pfister"
natural: "P123"
expected: "P236"
```

I'll probably whip up a test suite for this, because all that is there now is a few benchmarks.

**Comment by derrickpelletier** [comment]
I'll check a few other implementations against this as well.

Is there a reason natural seems to prefer internal libs rather than external dependencies?

**Comment by chrisumbel** [comment]
Those two examples involved some interesting double-consonants at the beginning. My gut tells me our implementation trips on that. I'd love to see a test suite. Thanks for report.

Will respond to second comment later -- longer explanation.

**Comment by derrickpelletier** [comment]
Just pulled down the latest master and though those were fixed, there are a bunch more that are not matching up now, that were before:

```
"Jackson"
expected: J250
natural: J500
-----------
"Tymczak"
expected: T522
natural: T520
-----------
"Gauss"
expected: G200
natural: G000
-----------
"Lukasiewicz"
expected: L222
natural: L200
-----------
"manhattan"
expected: M535
natural: M350
```

**Comment by chrisumbel** [comment]
By any chance could you create a test with these and commit it?

**Comment by chrisumbel** [comment]
But pull d883f4b  first
