### ISSUE TITLE
How can I get frequency words and weigh documents?

### ISSUE THREAD

**Issue by jbowden1982** [NaturalNode/natural#229]
So we are using Bayes classifier and I was trying to figure out how to get the number of times a word is mentioned across all the documents in the classifier, specifically I want to generate an array with dictionaries with the word and the times that word is mentioned.  Also in the project I am working on we have different data structures that carry different level's of importance.  Is there a way I can weigh a document to have more of an effect than another document?

Any help would be greatly appreciated thank you.

**Comment by anubisthejackle** [comment]
PHP has a useful tool called substr_count that lets you count a sub string
in a block of text. Using this, and iterating a counter field in an array
could solve this for you.

**Comment by TheDailySpank** [comment]
In the training file there is a docs section that contains the text of all the trained documents, including repetitions.

docs[n].text[i]

Push those items to an array and then feed it to something like this: http://stackoverflow.com/questions/12749200/how-to-count-array-elements-by-each-element-in-javascript
