### ISSUE TITLE
Case tokenizer?

### ISSUE THREAD

**Issue by alexlangberg** [NaturalNode/natural#245]
Hi there

This is kind of a pull request. During my experiments with text tokenizing I fell upon this idea, by a user named Seagull on SO:

http://stackoverflow.com/a/26482650/2762235

Basically, it takes each character in a string and compares the lowercase and the uppercase of the character. If they are equal, it is most likely a special character and is discarded. This means that special characters that are valid letters to languages but not the English alphabet are still preserved, without having to whitelist characters for each specific language. The downside is, of course, that it does not work with languages that do not use letter case.

I've taken this idea and expanded on it a bit, implementing it as a tokenizer for natural. I've copied the tests from all tokenizers of languages that use letter case (e.g. not farsi and japanese) and they seem to pass just fine. I've also added tests for a bunch of more languages that seem to work fine, although Dutch seems to need an override to preserve apostrophes? More input on this from native speakers would be great.

The result can be seen here:
https://github.com/alexlangberg/natural/blob/master/lib/natural/tokenizers/tokenizer_case.js
https://github.com/alexlangberg/natural/blob/master/spec/tokenizer_case_spec.js

I think this could be a great general purpose tokenizer, as it seems to work pretty well with quite a bit of languages, without resorting to whitelists. As I consider this kind of experimental, I haven't yet taken licenses/attribution from the things I've copied (only from this same project) into account yet, as I'm not sure exactly how this works out on a project like this. Sorry, no harm intented. The name is perhaps not the best and could easily be changed. I just wanted to see if this would be interesting?

What do you guys think?

**Comment by kkoch986** [comment]
its an interesting idea, id be happy to merge it as its own tokenizing method

**Comment by alexlangberg** [comment]
Yeah, honestly I have no idea what problems might come up down the road, as I only speak a handful of western languages myself. But I'd consider that a minor problem.

What about the copyright notices that are in all the tokenizer specs? I mean, I've taken tests from other specs and put in my own. Should I make a new copyright notice that attributes everyone that contributed? I don't feel like stepping on anyone's toes. :)

I'd be happy to do a pull request then.

**Comment by alexlangberg** [comment]
I've added people to the notices and made a pull request:

https://github.com/NaturalNode/natural/pull/246

**Comment by kkoch986** [comment]
Perfect will check it out asap thanks!
