### ISSUE TITLE
Naive Bayse classifier documents

### ISSUE THREAD

**Issue by tarrynn** [NaturalNode/natural#249]
Hi guys,

First of all this lib is awesome. Great work on it so far.

Maybe it's a dumb one, but I have a question (it might become a feature request, it's up to you guys as I'm not really into node.js / js development myself to hack away at this lib): 

Does the classifier only accept arrays of strings ? I've been passing arrays (always the same length) of computed (float) values and training the classifier on those entries, but when trying to classify similar arrays, I always get bogus values returned by the classifier.

Here's an example:

I'm training the classifier with [1.01, 0] for label 'a', [0, 1.05] for label 'b'. When trying to classify [1, 0] i get returned the same value for both 'a' and 'b', while it should have a higher chance of being in label 'a'.

Cheers

**Comment by Volox** [comment]
The classifier is based on text i think you might want to use [brain](https://github.com/harthur/brain) or [synaptic](https://github.com/cazala/synaptic/) for a numeric approach.

**Comment by kkoch986** [comment]
I would agree with @Volox the natural classifier is better for text classification and doesnt really work with non-discrete classifications
