### ISSUE TITLE
Natural cannot be used with browserify

### ISSUE THREAD

**Issue by DavidBruant** [NaturalNode/natural#253]
[Browserify](https://www.npmjs.com/package/browserify) emits en error message:
`Error: Cannot find module 'WNdb' from '<path>/node_modules/natural/lib/natural/wordnet'`

Also https://github.com/NaturalNode/node-sylvester/issues/4 prevents browserify usage.

One way to fix the issue would be to add `WNdb` as dependency of `natural`. In the meantime, I use browserify's `--ignore WNdb` option.

**Comment by azu** [comment]
FYI: "browser" field help to ignore a module for browserify.

- https://gist.github.com/defunctzombie/4339901#replace-specific-files---advanced
- https://github.com/substack/browserify-handbook#browser-field

**Comment by kkoch986** [comment]
i think this has been discussed in #25 and #189 but im pretty sure it stems from the fact that the WNdb module is not installed by default in natural hence it would not be present in the node_modules folder unless explicitly isntalled
