### ISSUE TITLE
Using natural in Meteor

### ISSUE THREAD

**Issue by 57even** [NaturalNode/natural#255]
Will it be possible to use natural in Meteor?

I have tried https://github.com/quietcreep/meteor-natural/ but it's not maintained and https://github.com/meteorhacks/npm only allows server side usage.

**Comment by kkoch986** [comment]
we dont really support it, as i've mentioned in #160 and #164 ive never really used it so i cant offer much help to that end, im sure there are people in the meteor community who can help and id certainly entertain a PR which could improve our compatibility with meteor if you do make some progress!
