### ISSUE TITLE
How to do multi-label classification?

### ISSUE THREAD

**Issue by jefffriesen** [NaturalNode/natural#265]
Does Natural have a way to do multi-label classification? Something along the lines of this: https://github.com/erelsgl/limdu#multi-label-classification

**Comment by Hugo-ter-Doest** [comment]
The classifiers return an array as follows:
```javascript
[ { label: 'buy', value: 0.39999999999999997 },
  { label: 'sell', value: 0.19999999999999998 } ]
```
So you could select multiple highest ranking classes as you result. Otherwise, there is no multi-label classification.

Hugo
