### ISSUE TITLE
Support for running in a browser

### ISSUE THREAD

**Issue by KevinGrandon** [NaturalNode/natural#266]
I'm aware of a few issues where people have had varying levels of success packaging natural for the browser, including: https://github.com/NaturalNode/natural/issues/25

I'd like to understand if there's any official plans to make this work, or if you would accept patches into the core to allow this to work in the browser.

**Comment by kkoch986** [comment]
There aren't currently any official plans, i would be more than happy to merge PRs depending on what they do versus the direction of everything else, currently my main goal is doing some reorganization and getting things more maintainable/salable which is taking precedence over browser-compatibility

**Comment by cyclomaticsegal** [comment]
Salable? Is there some official post/mention somewhere about natural going commercial and all that implies?

**Comment by kkoch986** [comment]
haha sorry about that _scalable_*

**Comment by Hugo-ter-Doest** [comment]
See [#25](https://github.com/NaturalNode/natural/issues/25).
Closing this one.

**Comment by Hugo-ter-Doest** [comment]
Removed most of the dependencies on <code>fs</code> and added a Gulp/Webpack configuration that runs specs in the browser.
