### ISSUE TITLE
Documentation Volunteer

### ISSUE THREAD

**Issue by keonkim** [NaturalNode/natural#267]
I am going to use this library for my personal project, and it consists of analyzing the code beneath.
And while doing that, I also want to contribute to this project with a more detailed documentation (it is both for my own study purpose and opensource contribution).

I was curious if you would let me merge the documents with the original package, if I am done writing it.
my docs will be inside `./doc` folder

**Comment by kkoch986** [comment]
absolutely! improved documentation has been on our wishlist for awhile. What format were you planning on writing the documentation in?

**Comment by keonkim** [comment]
I haven't thought about it much now that I am only in beginning stage, I was thinking perhaps making this as a static website with jekyll like this (http://bruth.github.io/jekyll-docs-template/) so the url will be like https://naturalnode.github.io .

Docs that I am about to write should include overview of classes, basic tutorial (the examples in the github), and api descriptions.
api docs will include the basics description of the algorithm, list of parameters, output, and simple usage. I might stress more on usage since it is more practical.

Also, if documentation about how to contribute to this project will also be helpful.
I am looking to add Korean language support, but it doesn't seem to have guide on that.

**Comment by Psarna94** [comment]
@keonkim I would like to contribute to the docs as well. I am a beginner to open source contribution. Probably this is a good place for me to start. Probably you can guide me as well.

**Comment by keonkim** [comment]
@Psarna94 That is awesome. Lets definitely work on this together. I've been reading the articles (curated here https://github.com/keonkim/awesome-nlp) to have firm understanding of NLP. You might also want to try that first as well, if you haven't already. You can contact me via keon.kim@nyu.edu

@kkoch986 Would writing docs on different repository (for web docs) a good choice?
If  yes, can you set up a repo under NaturalNode and give me access to it or should I work independently?

**Comment by kkoch986** [comment]
I guess making it through the github pages would be easiest, ill try to get that set up first and then we can figure out where to go from there. IIRC it just makes another branch and attaches it to this repo which isnt what i would say is my favorite approach but i havent looked at github pages in awhile so let me see if there are any better options available.

**Comment by keonkim** [comment]
@kkoch986 github pages would be my favorite. If you can just open repo, I can take care of the rest... Another option might be using github wiki like torch7 cheatsheet (https://github.com/torch/torch7/wiki/Cheatsheet)

**Comment by kkoch986** [comment]
I tihnk the best way to process is to accept PRs on the gh-pages branch of this project that way we can use http://naturalnode.github.io/natural/ I also have naturalnode.com which i can forward over to that.

The branch is created and ill do my best to be quick and responsive with the PRs on that branch. Thanks!!

**Comment by keonkim** [comment]
@kkoch986 That would be great! I'll keep you posted on the process. thanks!

**Comment by Hugo-ter-Doest** [comment]
Documentation is from now on Github pages http://naturalnode.github.io/natural/ using a Read the Docs template.

gh-pages is the branch for documentation. docs is the folder.
