### ISSUE TITLE
MEAN STACK DEVELOPER + NLP - AI TECH FIRM - NYC TOP DOLLAR - FULL TIME - AWS

### ISSUE THREAD

**Issue by alexgutterson** [NaturalNode/natural#270]
A client of mine is looking for exceptional engineers who specialize in the MEAN stack. They are located in midtown NYC and can pay top dollar. The firm is focused on AI/NLP and is looking for a strong foundation with both MEAN and AWS. Python and Java are plus skills.

If anyone is interested in hearing more, or would know someone that could possibly be interested you can reach me directly via email or over the phone. Otherwise don't hesitate to respond via GitHub.

Cheers!
Alex

Alexander Gutterson
CEO/Founder
Jay Alexander LLC
(E) Alex@jAlexanderLLC.com
(T) 646-979-0709 (feel free to text)

**Comment by kkoch986** [comment]
this is definitely not the right place for this, sorry

**Comment by suminksudhi** [comment]
Hello Alex,
I am a software engineer good working expertise in MEAN stack and have worked on AWS as well.I would like to know more about this opportunity. 
You could contact me back via mail,skype or my phone.
Regards
Sumin K SudhiSkypeId: dev.suminPhone: +918103574972
