### ISSUE TITLE
incorrect format of String Distance

### ISSUE THREAD

**Issue by parit90** [NaturalNode/natural#273]
The String Distance format between two string is incorrect, it should not be in Real number , the string distance should be in Natural number.

eg.  
input 1: abcsyz
input 2: abdsy
if substitution take cost of 2 ,insertion take cost of 1 and deletion take cost of 1,
then the answer should be 3. that is to transform input1 into input2 it will take cost of 3 .
2 for the substitution for 'd' in input2 and 1 for the insertion at the end of input2 that is 'z'.

I hope you are understanding my point. The cost should be integer rather then float point as you discussed in documentation of NLP node.

one more thing . are you applying EDIT-Distance(DP approach)  to calculate the string distance between two input strings.? 

This is also be true for 'levenshtein distance'.

**Comment by Hugo-ter-Doest** [comment]
We have a number of algorithms for string distance. Some have (or should have) an integer output, like Hamming distance. Some have a real number as output, such as Jaro-Winkler. Which algorithm does not give the right output? So we can fix that.

Hugo
