### ISSUE TITLE
tfidf measure bug?

### ISSUE THREAD

**Issue by sugang** [NaturalNode/natural#284]
Hi all,

I ran the tfidf example but the measure I got is different from the example:

This is the output I got from node console:
node --------------------------------
document #0 is 1
document #1 is 0
document #2 is 1
document #3 is 2
ruby --------------------------------
document #0 is 0
document #1 is 1.2876820724517808
document #2 is 1.2876820724517808
document #3 is 0

This is the output I got from the example page:
node --------------------------------
document #0 is 1.4469189829363254
document #1 is 0
document #2 is 1.4469189829363254
document #3 is 2.8938379658726507
ruby --------------------------------
document #0 is 0
document #1 is 1.466337068793427
document #2 is 1.466337068793427
document #3 is 0

They are very different. I am not sure which one is correct...

**Comment by kkoch986** [comment]
interesting, ill try to check it out asap

**Comment by adraghici** [comment]
Any updates on this? Encountering the same thing in 0.4.0.

**Comment by kkoch986** [comment]
just looked it over, seems to me like the output you are getting is correct. its passing all of the [unit tests](https://github.com/NaturalNode/natural/blob/master/spec/tfidf_spec.js) which show exactly how the calculation is done.

for the first example idf is computed as `var idf = 1 + Math.log((this.documents.length) / ( 1 + docsWithTerm ));` which is `1 + log(4 / (1 + 3)) = 1 + 0 = 1`

**Comment by kkoch986** [comment]
going to re-run all of the examples and make sure they are all correct. thanks for pointing this out!
