### ISSUE TITLE
TfIdf - Russian?

### ISSUE THREAD

**Issue by San2k** [NaturalNode/natural#285]
Hi!

Can anyone help me fix TfIdf for Russian lang? Any Tips?

Ty.

**Comment by felikz3** [comment]
you need to be more precise. what is the problem with tfidf for the language of russia?

**Comment by San2k** [comment]
Its just not working with Russian , i guess. Or i don't understand how to set it up.

Here is a screenshot: https://monosnap.com/file/3XSVimkKPioCB90RtY091M5c4iBF28

**Comment by San2k** [comment]
Sorry. GitHub was lagging. Closed it by accident.

**Comment by kkoch986** [comment]
so it looks like you have to change the tokenizer to the russian tokenizer:

```javascript
var natural             = require('../lib/natural/');
var tokenizer			= natural.AggressiveTokenizerRu;

var tfidf = new natural.TfIdf();
tfidf.setTokenizer(new tokenizer());

tfidf.addDocument("This is a test ая");
tfidf.addDocument("Another thing that has all different words except test ая");

console.log("ая");
tfidf.tfidfs("ая", function(i, measure) {
	console.log(i, measure);
});
```

the output is:
```
ая
0 0.5945348918918356
1 0.5945348918918356
```

whereas without changing the tokenizer:

``
