### ISSUE TITLE
How to use the tokenizer language file

### ISSUE THREAD

**Issue by taviroquai** [NaturalNode/natural#298]
Hi,

How to use the tokenizer language file?

Thanks

**Comment by Hugo-ter-Doest** [comment]
I'm not sure what you mean? Do you mean the fact that there are different tokenizers for languages?

Hugo

**Comment by taviroquai** [comment]
@Hugo-ter-Doest Yes, it is not clear in README how to use it for Portuguese. Can you help please?

**Comment by Hugo-ter-Doest** [comment]
In the spec folder you find a unit test that gives some example of the tokenizer for Portugese:
aggressive_tokenizer_pt_spec

Just require the module, create a tokenizer and call the tokenize method:
```javascript
var Tokenizer = require('../lib/natural/tokenizers/aggressive_tokenizer_pt'),
    tokenizer = new Tokenizer();
console.log(tokenizer.tokenize('isso é coração'));
```
Output:
```javascript
[ 'isso', 'é', 'coração' ]
```

Hugo

**Comment by taviroquai** [comment]
@Hugo-ter-Doest Thanks! Could this be added to docs? I close for now.

**Comment by Hugo-ter-Doest** [comment]
Yes will add it to the README.

It is better to say this to create a tokenizer for Portugese:
```javascript
var natural = require('natural');
var tokenizer = new natural.AggressiveTokenizerPt();
```

Hugo
