### ISSUE TITLE
Support for german stemmer

### ISSUE THREAD

**Issue by thomasfr** [NaturalNode/natural#30]
Would be great to have a stemmer for the german language. 
Maybe this is a good starting point? https://gist.github.com/2199965

**Comment by Hugo-ter-Doest** [comment]
Added Porter Stemmer for Dutch. I should say that the Porter algorithm makes mistakes in Dutch and that my implementation stems 305 of the 45669 examples in the snowball file. That is less than 1% failure. Also the Snowball file contains wrong examples; for instance afvalstortplaats is stemmed as afvalstortplat, which is wrong.

Hugo

**Comment by webia1** [comment]
News?

**Comment by Hugo-ter-Doest** [comment]
> Hi, I could try to do a simple base implementation based on top of the Gist i provided. but i have to check the license first. 

I checked the license: 
```
/*
 * Original author: Joder Illi
 * 
 * Copyright (c) 2010, FormBlitz AG
 * All rights reserved.
 * Implementation of the stemming algorithm from http://snowball.tartarus.org/algorithms/german/stemmer.html
 * Copyright of the algorithm is: Copyright (c) 2001, Dr Martin Porter and can be found at http://snowball.tartarus.org/license.php
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, is covered by the standard BSD license. 
 * 
 */
```
As I see it BSD licensed code can be integrated in a MIT licensed code base as long as the the added code has the original (BSD) license.

**Comment by Hugo-ter-Doest** [comment]
I am also considering jsSnowball transpiled from Java sources. It is licensed with BSD 3.0 which can be combined with MIT license as well.

Source can be found here:
https://github.com/mazko/jssnowball

**Comment by Hugo-ter-Doest** [comment]
See #663 for progress

**Comment by Hugo-ter-Doest** [comment]
#663 is merged.
