### ISSUE TITLE
Load Classifier return `undefined`

### ISSUE THREAD

**Issue by kennetham** [NaturalNode/natural#304]
I was testing out the loading of classifier.

Based on the sample code provided: (https://github.com/NaturalNode/natural/blob/master/examples/classification/recall.js)

``` node
var natural = require('natural'),
    classifier = new natural.BayesClassifier();

natural.BayesClassifier.load('classifier.json', null, function(err, classifier) {
    console.log(classifier.classify('did the tests pass?'));
    });
```

The results returned an `undefined`.

Any idea what did I miss?

**Comment by ntieman** [comment]
This example requires the data file **classifier.json**. Run the **store.js** example first to generate the file.

**Comment by kennetham** [comment]
I did that. I ran the classifier.js, then store.js to store it, I have the classifier.json already, but somehow it was unable to read the json file on load. Any idea why?

**Comment by ntieman** [comment]
I do not. Running recall.js before store.js was enough for me to reproduce the undefined error, and running them in order fixed it for me.

**Comment by kennetham** [comment]
So what happens if I have an existing classifier.json, I would still have to go through the process of classifiying and storing before retrieval?

I'll try again. Thank you.

**Comment by Vsevosemnog** [comment]
So how to resolve this problem?

I created a classifier, trained it and saved it to a file

then in other project i try to load this model from my file, and the model is undefined

**Comment by Hugo-ter-Doest** [comment]
I tried the examples and they work fine. First run `store.js` and then run `recall.js`.
