### ISSUE TITLE
Logistic Regression Classifier locks up when training the same phrase on multiple classifications

### ISSUE THREAD

**Issue by dyladan** [NaturalNode/natural#309]
When training on a logistic regression classifier, if multiple classifications are trained on the exact same phrase the CPU locks up during the call to `train()`. Our app lets users define their own classifications so this is an important case for us to handle. Right now we are just testing for exact string matches when users enter training data.

Afflicts the LogisticRegressionClassifier but does not seem to affect BayesClassifier

``` javascript
const n = require('natural');
const c = new n.LogisticRegressionClassifier();

c.addDocument("Take me out to the ballpark", "yankees");
c.addDocument("Take me out to the ballpark", "redsocks");

c.train() // CPU locks up during this call

console.log(c.classify("Take me out to the ballpark"));
```

**Comment by bansalvks** [comment]
I am facing the same issue. Please help.

**Comment by bansalvks** [comment]
I request the owner to at least reply to our concerns.

**Comment by kkoch986** [comment]
i can confirm im seeing the issue ill try to get a fix out asap

**Comment by kkoch986** [comment]
thinking its related to https://github.com/NaturalNode/apparatus/issues/13

**Comment by kkoch986** [comment]
just merged a fix for this in apparatus and bumped the version to 0.0.10 thanks @Finkes 

last step would be to update the dependency in natural

**Comment by Hugo-ter-Doest** [comment]
Updated the dependency and published a new version on NPM.

Hugo
