### ISSUE TITLE
Natural Node not working with Hindi/Devanagiri scripted text

### ISSUE THREAD

**Issue by sanjibnarzary** [NaturalNode/natural#314]
I am not familiar with Natural Node, I am just evaluating the Natural node whether I can choose it for my project not. I tried to tokenize our Bodo word which uses devanagiri or hindi script, but it not giving any tokenized words where as it works perfectly with english text

`var natural = require('natural');

var bodoText = `नेसारेल नद आ खामानि मावयाखै |`;

var englishText = `Natural Node is working fine!`;

tokenizer = new natural.WordTokenizer();

var bodoText = tokenizer.tokenize(bodoText)

var englishText = tokenizer.tokenize(englishText)

console.log(bodoText);

console.log(englishText);`

it is giving me output

`
[]

[ 'Natural', 'Node', 'is', 'working', 'fine' ]

`

So I am just curious, whether Natural Node works with Hindi scripted text or not.

**Comment by decoderling** [comment]
Hindi/Devanagari does not currently have a tokenizer made in Natural. You could write one though!

Also it might be a good idea to have the documentation list the available tokenizer languages vs having to look in the source folder to determine if a language is supported.

**Comment by kkoch986** [comment]
yea i totally agree adding to the documentation would make it a lot easier. We had discussed awhile ago adding some kind of standardization around the other languages in the code which would make documenting easier but its a pretty big project

**Comment by Hugo-ter-Doest** [comment]
The README now contains an overview of supported languages by the tokenizers. This was done by [Mehdi El Fadil](https://github.com/mef) in PR [#405](https://github.com/NaturalNode/natural/pull/405).

Hugo
