### ISSUE TITLE
Reduce published files

### ISSUE THREAD

**Issue by ravenjohn** [NaturalNode/natural#315]
I just saw this package because it contains large spec files. It would be better if only the important files are published in npm. You can use `"files"` prop in package.json to specify files to be published.

**Comment by Hugo-ter-Doest** [comment]
I think it is important that unit tests are delivered with the package. It allows you to test the package after deploying. I agree that the natural module holds a lot of files, but maybe you can strip it for your own purposes. 

Hugo
