### ISSUE TITLE
Support French

### ISSUE THREAD

**Issue by eXon** [NaturalNode/natural#319]
I would like to help add support for French on the library. Where is the best place to start something small? :)

**Comment by c100k** [comment]
Can help too.

**Comment by kkoch986** [comment]
great! i just answered a similar question here: https://github.com/NaturalNode/natural/issues/324

Stemmers and tokenizers seem like good starting places to me, unfortunately it looks like someone beat you to the punch on those. Is there some functionality youre looking for that we dont have? 

the [normalizer](https://github.com/NaturalNode/natural/tree/master/lib/natural/normalizers) looks like its missing french.

**Comment by kkoch986** [comment]
im also noticing some of the french libraries we have may not be fully tested so maybe cross referencing what we have implemented with whats tested and see if there are improvements there.
