### ISSUE TITLE
classifier giving wrong result

### ISSUE THREAD

**Issue by bansalvks** [NaturalNode/natural#322]
I have started learning Natural Language Processing and have already started stumbling.

**Problem**

I am training my document with several scenarios as shown below

    /// importing package
    var natural = require('natural');
    var classifier = new natural.BayesClassifier();

    /// traning document
    classifier.addDocument("h", "greetings");
    classifier.addDocument("hi", "greetings");
    classifier.addDocument("hello", "greetings");
    classifier.addDocument("data not working", "internet_problem");
    classifier.addDocument("browser not working", "internet_problem");
    classifier.addDocument("google not working", "internet_problem");
    classifier.addDocument("facebook not working", "internet_problem");
    classifier.addDocument("internet not working", "internet_problem");
    classifier.addDocument("websites not opening", "internet_problem");
    classifier.addDocument("apps not working", "internet_problem");
    classifier.addDocument("call drops", "voice_problem");
    classifier.addDocument("voice not clear", "voice_problem");
    classifier.addDocument("call not connecting", "voice_problem");
    classifier.addDocument("calls not going through", "voice_problem");
    classifier.addDocument("disturbance", "voice_problem");
    classifier.addDocument("bye", "close");
    classifier.addDocument("thank you", "feedback_positive");
    classifier.addDocument("thanks", "voice_problem");
    classifier.addDocument("shit", "feedback_negeive");
    classifier.addDocument("shit", "feedback_negeive");
    classifier.addDocument("useless", "feedback_negetive");
    classifier.addDocument("siebel testing", "siebel_testing")

    classifier.train();

    /// running classification
    console.log('result for hi');
    console.log(classifier.classify('hi'));
    console.log('result for hii');
    console.log(classifier.classify('hii'));
    console.log('result for h');
    console.log(classifier.classify('h'));

    

> Output
>     
>     result for hi:
>     greetings

>     result for hii:
>     internet_problem

>     result for h:
>     internet_problem

As you can see in the result of the key work `hi` the value is coming correct but if I misspelled `hi` for `hii` or `ih` then it's giving a wrong result. I am not able to understand how does classification works and how should I train the classifier or is there a way to find out that the result of classification is wrong so that I can request an user to input again.

Any help or explanation or anything is highly appreciated. Many thanks in advance.

Please consider me as a noob and forgive for any mistake.

**Comment by Stigjb** [comment]
This doesn't seem too unexpected. Neither `'h'` nor `'hii'` occur in the training data, and when the classifier doesn't know what to do with the input, it gives you the most frequent class from training, which is `"internet_problem"` with 7 instances.
