### ISSUE TITLE
Support Italian

### ISSUE THREAD

**Issue by mrigo** [NaturalNode/natural#324]
Hey hi!
I would like to help add support for Italian on the library.
Which is the best way to start :) ?

Thanks!
\m

**Comment by kkoch986** [comment]
Thanks! always love getting more language support.

we have lots of different things you could implement in italian. You can browse through the library here https://github.com/NaturalNode/natural/tree/master/lib/natural youll notice a lot of files with extensions like `.es.js` those are language specific implementations you can see how they work.

Seems like good starting points are [Tokenizers](https://github.com/NaturalNode/natural/tree/master/lib/natural/tokenizers) and [Stemmers](https://github.com/NaturalNode/natural/tree/master/lib/natural/stemmers)

hope to see some PRs soon!

**Comment by kkoch986** [comment]
theres also [Inflectors](https://github.com/NaturalNode/natural/tree/master/lib/natural/inflectors) which doesnt have anything in italian
