### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by adrianmcli** [NaturalNode/natural#331]
The last release on NPM was 11 months ago by @chrisumbel. Since then, there have been more than 10 pull requests merged into master. Isn't it about time that someone (who has the permissions) release a new version so we can use all the new stuff that was merged in?

I don't see the point of my last PR being merged if no one is going to use it.

cc @kkoch986 and @silentrob

**Comment by bansalvks** [comment]
I wish they start full-fledged development and make this project complete with the latest NLP projects.

**Comment by adrianmcli** [comment]
I have a feeling that the maintainers have given up. If that's the case, it's probably a good idea to add new maintainers so we can keep this project going.

**Comment by bansalvks** [comment]
Its a good project. I do not know why anyone would give up on this. But if they quit then its a sad news for all.

**Comment by adrianmcli** [comment]
If there is no response for a few more weeks, I suggest we start a fork.

**Comment by Hugo-ter-Doest** [comment]
+1

**Comment by kkoch986** [comment]
sorry everyone just pushed it out now, ill try to check out the PRs tonight and get them all taken care of as well

**Comment by adrianmcli** [comment]
Welp, I guess that fixes this issue! Thanks @kkoch986

**Comment by silentrob** [comment]
It took a very short amount of time for this thread to almost go nuclear. Lets all do more to work together! If anyone else is interested in collaborating in a more serious way I'm sure that would be more than welcome.

**Comment by adrianmcli** [comment]
@silentrob I don't mind taking a bigger role. That being said, maybe I haven't quite proven myself yet, but I am eager to improve this library.

**Comment by bansalvks** [comment]
Awesome, It is so great to know that we are moving ahead to achieve new milestones, seriously. Great!! can I join the crew :)  How?

God Speed!
