### ISSUE TITLE
Bug: jaro-winkler returns 1.0 on comparing jaroWinklerDistance('00000000000333', '00000000000033')

### ISSUE THREAD

**Issue by jfseb** [NaturalNode/natural#332]
The jaro algorithm implementation appears to be flawed, 
it returns 1.0 for disctinct strings. 

Adding the following test condition to 
\spec\jaro-winkler_spec.js

    it('should treat simple distinct strings distinct', function () {
        expect(jaroWinklerDistance('00000000000333', '00000000000033')).toBeLessThan(1);
    });

makes the test fail.   The strings are obviously distinct. 

The error is in the jaro implementation, 
 
There appears to be a jaro implementation which is similarly performanct and 
makes this condition hold in    https://github.com/Yomguithereal/talisman/blob/master/src/metrics/distance/jaro.js   

However, they got the Winkler adjustments wrong, (which is here ok), 
resulting in distinct strings with a long common prefix having a score > 1.0 ;-) 

-> 
a=s_bce_68000274
b=s_bce_68000264
jw=1.010

Perhaps you can combine the two working parts [your winkler, their jaro ],
if you agree on the licenses & copyrights.

**Comment by decoderling** [comment]
I haven't tested your specific problem yet, but I made a Pull Request updating the Jaro Winkler function here: https://github.com/NaturalNode/natural/pull/329

It's pending merge due to broken builds with an older version of node.

 - David

**Comment by kkoch986** [comment]
should be fixed and merged now, will send out a new version probably tomorrow just want to give a once over to a few more things
