### ISSUE TITLE
Feature request: Damerau Levenshtein distance

### ISSUE THREAD

**Issue by syzer** [NaturalNode/natural#333]
https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance

Quite often Its more useful than plain Levenshtein. 
Would be possible to add it?

**Comment by kkoch986** [comment]
its definitely possible! my bandwidth is pretty tied up right now but we always welcome pull requests :wink:

**Comment by syzer** [comment]
ok assign to me.

**Comment by syzer** [comment]
can it be separate package, or shall i PR to core?

**Comment by kkoch986** [comment]
i think a PR would be great
