### ISSUE TITLE
Is there a way to find the statement's sentiments? e.g. negative, positive, sarcastic?

### ISSUE THREAD

**Issue by bansalvks** [NaturalNode/natural#334]
First of all, You people are amazing and NarutalNode is damn awesome.... It feels so great that I came across such a good library. However, there is something I am looking for but not able to find and that is Sentiment analysis.

Could you confirm that is there a way to analysis sentiments of a statement, like if it is a sarcastic statement or a positive/negative statement?

Looking forward to your guidance. Please keep the good work up.

Many best wishes from me!!!

**Comment by kkoch986** [comment]
we dont currently have a built-in sentiment analysis alogrithm

**Comment by Hugo-ter-Doest** [comment]
Almost finished the Sentiment Analyzer, see [https://github.com/Hugo-ter-Doest/natural/tree/master/lib/natural/sentiment](https://github.com/Hugo-ter-Doest/natural/tree/master/lib/natural/sentiment)

Hugo
