### ISSUE TITLE
Jaro Winkler - Wrong Measurment

### ISSUE THREAD

**Issue by cbernecker** [NaturalNode/natural#340]
I compared similar strings with each other and used the 'natural' and 'jaro-winkler' module. Both of them delivered different outcomes.

1. Example:
s1 = what are the memory requirements for XYZ?
s2 = What is the server memory requirement for XYZ?

JARO: 0.5584175084175085 (natural)
JARO: 0.804288499025341   (jaro-winkler)

Seems that you also want to perform an optimization (see #280) in general based on the mentioned (jaro-winkler) module.

**Comment by chrisumbel** [comment]
I believe this to be related to capitalization. Natural ignores case which is in retrospect a poor design decision. #306 made an attempt at addressing it, but there were concerns about breaking old code. 

I'm becoming less worried about breaking old code and more interested in making sure the algorithm is implemented correctly. @kkoch986 , what do you think?

**Comment by Hugo-ter-Doest** [comment]
Now that we have removed case sensitiveness from the algorithm the score is much closer to the jaro-winkler module:
0.8090835757855906

Hugo
