### ISSUE TITLE
Stemmer: "denies" to "deni", "simplifies" to "simplifi"?

### ISSUE THREAD

**Issue by httpdigest** [NaturalNode/natural#341]
The stemmer seems to have some issues relating to how English words ending with "y" use a third person singular conjugation ending with "ies".

**Comment by omijn** [comment]
These stems, although not English words, are actually correct. **deni** is the stem of **"denies"** and **"simplifi"** is the stem of **"simplifies"**. What is important is that inflected forms a word conflate to the same stem. This way, we can identify that **deny**, **denies**, **denied**, etc are all part of the same group. In a similar example, both **happy** and **happiness** get stemmed to **happi**.

**Comment by httpdigest** [comment]
Interesting! Thanks for the clarification. :)
