### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by wolf0x** [NaturalNode/natural#345]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "natural"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.7.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.7.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webworker-threads
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

**Comment by wolf0x** [comment]
webworker-threads somehow failed to install on Win10 machine and which impact the Natural. and checked webworker as well that there's no solution yet as not only single has this issue.

**Comment by roycetucker** [comment]
I'm seeing the same issue on Windows 10. I assume [node-gyp](https://github.com/nodejs/node-gyp#installation) is failing because I don't have either python or Visual Studio installed. 

I just ended up explicitly requesting version `0.5.0` for the time being.

**Comment by fisch0920** [comment]
I'm seeing this issue on node-alpine as well. Would love to not have a dependency on python for a popular node module like `natural`.

**Comment by anlausch** [comment]
+1

**Comment by kkoch986** [comment]
looks like npm supports `optionalDependencies` i would be in favor of putting it in there just to avoid failing to install. we only current use webworker threads for training classifiers in parallel so its definitely an optional feature. It would just take a little bit of refactoring to make sure that everything goes smoothly without it

**Comment by ryanwitt** [comment]
I've had the same problem on small cloud instances not big enough to support a build toolchain. The above PR is working for me in production using `npm install --no-optional`.

**Comment by kkoch986** [comment]
should be resolved now thanks @ryanwitt for the PR and everbody else for helping track it down!

**Comment by dispeakble** [comment]
***error***


if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files (x86)\Python35-32\python.exe", you can set the PYTHON env variable.
[...]

i have set my python path and pythonpath and just path with the directory iteself and executable. nothing works

I have python 3.5 installed
