### ISSUE TITLE
Nature Unable to Locate Bindings File in RunKit.

### ISSUE THREAD

**Issue by rayk** [NaturalNode/natural#346]
When attempting to run Natural from  NPM site in [RunKit](https://runkit.com/npm/natural). One encounters

> Error: Could not locate the bindings file. Tried:
>→ /app/available_modules/1493023968000/natural/node_modules/webworker-> threads/build/WebWorkerThreads.node

This can be reproduced by clicking on the link above and clicking running, this will throw the error immediately.

I should note that I have not been able to reproduce the above locally.

**Comment by kkoch986** [comment]
should be fixed as of (#354)

**Comment by AssKicker0214** [comment]
> Error: Could not locate the bindings file. Tried:
 → C:\coding\projects\blog\node_modules\_webworker-threads@0.7.12@webworker-threads\build\WebWorkerThreads.node
 → C:\coding\projects\blog\node_modules\_webworker-threads@0.7.12@webworker-threads\build\Debug\WebWorkerThreads.node

I got this

**Comment by OoDeLally** [comment]
Got the same error when running on `electron`.
Posted a proposition here https://github.com/NaturalNode/natural/issues/368

**Comment by Hugo-ter-Doest** [comment]
Adding Webworker-threads is manual now. So no problems should occur anymore in using natural with a framework like electron.

Hugo
