### ISSUE TITLE
Is this a typo: LongestPathTree

### ISSUE THREAD

**Issue by cikasfm** [NaturalNode/natural#348]
Somehow I'm reading this section in the docs: [LongestPathTree](https://github.com/NaturalNode/natural#longestpathtree) which is actually talking about **ShortestPathTree**

Is this a typo of some sort or am I not getting the thing?

**Comment by cikasfm** [comment]
Created a pull request https://github.com/NaturalNode/natural/pull/349

**Comment by kkoch986** [comment]
im not totally familiar with the algorithm but based on this comment, i think you are probably correct.

```
/**
  *  The LongestPathTree represents a data type for solving the
  *  single-source longest paths problem in edge-weighted directed
  *  acyclic graphs (DAGs). The edge weights can be positive, negative, or zero.
  *  This implementation uses a topological-sort based algorithm.
  *  the distTo() and hasPathTo() methods take
  *  constant time and the pathTo() method takes time proportional to the
  *  number of edges in the longest path returned.
  */
```
