### ISSUE TITLE
Bayes Classifier Train Function Does Nothing

### ISSUE THREAD

**Issue by AgnibhaBose** [NaturalNode/natural#361]
BayesClassifier Train Function is doing no training. The Function is empty and parent's function is not being called. Please check and let me know. No Training is getting done whenever train is called. Please find below the code snippet and error.

var natural = require('natural');

var classifier = new natural.BayesClassifier();

classifier.addDocument('how do i', 'perform action');
classifier.addDocument('How is', 'query info');
classifier.addDocument('How are', 'query info');
classifier.addDocument('Why was', 'query info');
classifier.addDocument('Is it', 'query info');
classifier.train();
console.log(classifier.classify("How do I book a ticket');

Error:

/home/agnibha/WebstormProjects/FAQBuilder/node_modules/apparatus/lib/apparatus/classifier/classifier.js:39
		throw "Not Trained";
		^
Not Trained

**Comment by stalinb87** [comment]
You must wait for the training, 

classifier.events.on('doneTraining', () => {
   console.log(classifier.classify("How do I book a ticket');  
});
classifier.train();
remember to put the train method after events
