### ISSUE TITLE
Tokenizer splits words containing an accent

### ISSUE THREAD

**Issue by disklosr** [NaturalNode/natural#366]
**Expected**: the word 'vélib' represents a single token
**Actual**: The word 'vélib' is tokenized into two tokens.

``` js
var natural = require("natural");
var tokenizer = new natural.WordTokenizer();

console.log(tokenizer.tokenize("vélib")) //produces an array with two elements
```

**Comment by kkoch986** [comment]
you may want to try a tokenizer for a different language. you can see the supported languages here: https://github.com/NaturalNode/natural/tree/master/lib/natural/tokenizers
