### ISSUE TITLE
Can I generate replies with my output from my own model?

### ISSUE THREAD

**Issue by jenniferzhu** [NaturalNode/natural#371]
I can't find the plugin function information on the README page. Is it possible to extract entities from the query and use them as input to a customized function, so that the bot can reply with an output from the function?

**Comment by kkoch986** [comment]
not sure i totally understand your question. if youre looking for part of speech tagging we do have some relatively new support for that (see https://github.com/NaturalNode/natural#pos-tagger)

**Comment by jenniferzhu** [comment]
What I asked here is to train a name entity recognition (NER) model and then plug in a pre-trained NER model into the NaturalNode framework. Most of the time, we do not care about those common entities such as person and location, but specific groups of names such as drug name and side effect name. I like PoS, but can I add my own function?

**Comment by kkoch986** [comment]
not necessarily your own function but you can define rules according to here: https://github.com/NaturalNode/natural/blob/master/README.md#pos-tagger specifically the lexicon section.
