### ISSUE TITLE
Spellcheck Feature

### ISSUE THREAD

**Issue by choungchamnab** [NaturalNode/natural#372]
Do I need to add list of words for spellcheck manually ?  How many can it support ? If it is over 100,000 words , Does it affect on performance ?

**Comment by kkoch986** [comment]
it is backed by a trie data structure which is extremely efficient for prefix lookups so hits should be very fast regardless of the corpus size. misspelled word performance will vary depending on the acceptable edit distance but i imagine with 100k words it will experience some slowdown but i dont really have a quantification for it
