### ISSUE TITLE
Plurality of English nouns is inconsistent

### ISSUE THREAD

**Issue by cryptodigitator** [NaturalNode/natural#374]
console.log(nounInflector.pluralize('radius'));
console.log(nounInflector.pluralize('virus'));
console.log(nounInflector.pluralize('walrus'));

produces:

radii
viri
walruses

The distinction between Latin & Greek based words (the formal distinction in usage AFAIK) is inconsistent.

**Comment by rawpixel-vincent** [comment]
Can you provide the expected output?

**Comment by kkoch986** [comment]
they are all correct, from what i understand (i am certainly not an expert on the matter so feel free to correct me) theres only one way to do walruses (not walri) so we could do `viruses / radiuses / walruses` if we wanted to go that route im not really opposed but i also dont think we are necessarily being inconsistent

**Comment by LandonPowell** [comment]
@kkoch986 
https://english.stackexchange.com/questions/3838/viruses-or-virii 
It's viruses.
