### ISSUE TITLE
LogisticRegressionClassifier: unhandled infinite loop 

### ISSUE THREAD

**Issue by Finkes** [NaturalNode/natural#382]
If two classes contain exactly the same documents, the train() method will block infinitely.
I created the following code snippet which leads to this infinite loop:

```
let natural = require('natural')

var classifier = new natural.LogisticRegressionClassifier();

classifier.addDocument('test', 'class1');
classifier.addDocument('test', 'class2');

classifier.train(); // infinite loop

console.log('will not be logged')
```

However for 3 or more classes sharing the same document works:
```
let natural = require('natural')

var classifier = new natural.LogisticRegressionClassifier();

classifier.addDocument('test', 'class1');
classifier.addDocument('test', 'class2');
classifier.addDocument('test', 'class3');

classifier.train();

console.log(classifier.getClassifications('test'))
```

**Comment by reblws** [comment]
Tried debugging and seems and ended up in an infinite loop at [logistic_regression_classifier.js#L58](https://github.com/NaturalNode/apparatus/blob/master/lib/apparatus/classifier/logistic_regression_classifier.js#L58).  The `learningRate` eventually hits 0 and doesn't break because `learningRateFound = false`. Maybe there should be a break or error case if `learningRate` hits 0 exactly?

**Comment by Finkes** [comment]
are there any updates on this ?

**Comment by vishalsinha-mubble** [comment]
Please comment if this has been fixed. I am facing the same problem.

**Comment by Finkes** [comment]
I fixed it and opened a pull request but nobody is responding to that...

**Comment by Hugo-ter-Doest** [comment]
There are no pending pull requests as far as I can see. Can you help us with a (new) pull request?

Hugo

**Comment by Finkes** [comment]
the issue is part of the submodule called apparatus so I opened it there: https://github.com/NaturalNode/apparatus/pulls

**Comment by Hugo-ter-Doest** [comment]
I see. Unfortunately, I cannot commit to apparatus. I think we need @chrisumbel to do this.

Hugo

**Comment by Finkes** [comment]
@chrisumbel can you please verify the pull request?

**Comment by kkoch986** [comment]
hey just got it merged and pushed a new patch version of apparatus (0.0.10)

**Comment by Hugo-ter-Doest** [comment]
Updated the version of apparatus and published a new version on NPM.

Hugo
