### ISSUE TITLE
Load from JSON Object?

### ISSUE THREAD

**Issue by greggmojica** [NaturalNode/natural#389]
I am using the natural.BayesClassifier.load() method to load an ecternal JSON file. However, since my JSON is changing quickly, is it possible to load a JSON object (inline) instead of an actual file? If so, how is this possible with natural? Thank you!

**Comment by greggmojica** [comment]
@chrisumbel ?

**Comment by kkoch986** [comment]
i would start [here](https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/classifier.js#L425-L438) and [here](https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/bayes_classifier.js#L45-L54) looks like load in the bayes classifier just calls that restore function with the obj
