### ISSUE TITLE
Help with Vietnamese 

### ISSUE THREAD

**Issue by Javis1205** [NaturalNode/natural#390]
add vietnamese of tokenizers
`
var Tokenizer = require('./tokenizer'),
    util = require('util');

var AggressiveTokenizer = function() {
    Tokenizer.call(this);    
};
util.inherits(AggressiveTokenizer, Tokenizer);

module.exports = AggressiveTokenizer;

AggressiveTokenizer.prototype.tokenize = function(text) {
    // break a string up into an array of tokens by anything non-word
    return this.trim(text.split(/[^a-z0-9àáảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵđ]+/i));
};
`

**Comment by pvsong** [comment]
+1

**Comment by Hugo-ter-Doest** [comment]
Added your tokenizer to natural. See [#425](https://github.com/NaturalNode/natural/pull/425).
Thanks!
