### ISSUE TITLE
Bad json run time error

### ISSUE THREAD

**Issue by rajeshpachar** [NaturalNode/natural#392]
https://github.com/NaturalNode/natural/blob/master/lib/natural/distance/levenshtein_distance.js

line number: 96 in latest 0.5.5 release

function DamerauLevenshteinDistance(source, target, options) {
    var damLevOptions = _.assign(
        { transposition_cost: 1, restricted: false },
        options || {},
        **{ damerau: true },**
    );
    return levenshteinDistance(source, target, damLevOptions);
}

extra comma should be removed.

**Comment by Samurais** [comment]
Come to the same issue.

**Comment by andre0799** [comment]
same here

**Comment by sballesteros** [comment]
same here

**Comment by kkoch986** [comment]
sorry about that! just bumped the version should be fixed now
