### ISSUE TITLE
ensinArr should return longest match

### ISSUE THREAD

**Issue by dmarman** [NaturalNode/natural#398]
https://github.com/NaturalNode/natural/blob/8071055f103f2d9fead395c5b823e0b247fb13a7/lib/natural/stemmers/porter_stemmer_es.js#L54

as in the original algorithm is explained, this function should return the longest match/suffix.

This function will return the first suffix it finds which could be shorter that the one it should outputs. This makes failure in lot of words.

```
endsinArr(word, suffixes)
    {
        var matches = [];
        for(var i in suffixes) {
            if(this.endsIn(word, suffixes[i])){
                matches.push(suffixes[i]);
            }
        }
        var longest = matches.sort(function (a, b) {
            return b.length - a.length;
        })[0];

        if(longest){
            return longest
        } else {
            return '';
        }
    }
```

**Comment by kkoch986** [comment]
if you could work this into a PR id happily merge, dont have much time right now to really work on it and test it

**Comment by Hugo-ter-Doest** [comment]
Spanish stemmer has been updated.
