### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated

### ISSUE THREAD

**Issue by pournima108** [NaturalNode/natural#406]

**Comment by Hugo-ter-Doest** [comment]
Where in the code did you see this?

**Comment by Narretz** [comment]
I got this message from this line: https://github.com/NaturalNode/natural/blob/3514b94b8c5f2f035cdd985b1d33bbbb0c78088e/lib/natural/wordnet/wordnet_file.js#L56

Also added a PR https://github.com/NaturalNode/natural/pull/411

**Comment by Hugo-ter-Doest** [comment]
Thanks!
