### ISSUE TITLE
Indonesian stemmer crash on require/import

### ISSUE THREAD

**Issue by teddis** [NaturalNode/natural#409]
Dang, this wonderful-looking package crashes promptly on import. Who else is able to use this package? And it's sad it looks like this package is no longer actively maintained. I get this crash, and so far having trouble understanding how the word array can contain a function (avg). There is nothing adding a function to the end of the array! It would also be nice to disable undesirable features to save start-up time and space.

```
29928: zulmat
29929: zulu
29930: zurafah
29931: zuriah
29932: zus
avg: function () {
    return this.reduce((p, c) => p + c, 0) / this.length;
}

/node_modules/natural/lib/natural/stemmers/indonesian/stemmer_id.js:136
        word = word.trim();
                    ^
TypeError: word.trim is not a function
```

**Comment by teddis** [comment]
Oh looks like this was already addressed but trying to find it.

**Comment by teddis** [comment]
I have master 0.5.6 and this is a showstopper.

**Comment by Narretz** [comment]
Looks like this has been fixed on master, but not released: https://github.com/NaturalNode/natural/commit/0ce591f751e5b5b8839127977137e294eb06c770

**Comment by deepeshsunku** [comment]
I'm seeing this issue as well.

**Comment by ashwinkodialbail** [comment]
I get the same error.

**Comment by Hugo-ter-Doest** [comment]
The issue has been solved already. Please pull the most recent version of natural from github to prevent this error (instead of installing from NPM).

@kkoch986 could you please release a new version to NPM?

I will close the issue now.

Hugo
