### ISSUE TITLE
Swedish Stemming

### ISSUE THREAD

**Issue by sustained** [NaturalNode/natural#410]
I'd possibly be interested in adding Swedish stemming but I might need a bit of guidance.

Do you have a Gitter, Discord, ... for real-time discussion of the project/development?

**Comment by sustained** [comment]
Ah, I just saw that it already exists at least to some extent. Guess the README is outdated...

**Comment by Hugo-ter-Doest** [comment]
Ok, then I'll close it.

Hugo
