### ISSUE TITLE
Classifer docsToFeatures undefined FEATURES

### ISSUE THREAD

**Issue by nsantini** [NaturalNode/natural#413]
On line 128 of classifier.js we have:

`for (var feature in FEATURES) {`

FEATURES is never defined in the file. Not sure if this function is used at all, but this would be a breaking bug, unless there is something I'm missing

**Comment by Hugo-ter-Doest** [comment]
The variable <code>FEATURES</code> is passed to the environment of the threads by the following statement:
```javascript
threadPool.all.eval('var FEATURES = ' + JSON.stringify(this.features));
```
Then docsToFeatures is called:
```javascript
threadPool.all.eval(docsToFeatures);
```

(lines 175/176 of classifier.js)

Hugo
