### ISSUE TITLE
Readme mentions sentiment analyzer, but it seems to be missing once installed

### ISSUE THREAD

**Issue by eddieyanez** [NaturalNode/natural#421]
I can see the code in github, but not when installed via npm.

Thanks,

Eddie

**Comment by Hugo-ter-Doest** [comment]
Yes, we need an update of the NPM package. Ken will do an update soon.

Hugo

**Comment by eddieyanez** [comment]
Awesome, thanks!

**Comment by lula** [comment]
@Hugo-ter-Doest I guess the analyzer is also missing in [index.js](https://github.com/NaturalNode/natural/blob/master/lib/natural/index.js). As I was really eager to try it out I installed natural from git master branch but I couldn't use the sentiment analyzer as long as I didn't add the export  `exports.SentimentAnalyzer = require('./sentiment/SentimentAnalyzer');` in index.js. Perhaps it's something you're already aware of or most likely I'm simply missing something or misusing it :).  If you prefer (and certainly if my assumption is correct) I can also try to open a new PR for that.

@eddieyanez in case you were eager as I was to play with the sentiment analyzer and don't want to wait for the new npm package you can try the above workaround :)

**Comment by lula** [comment]
Thanks! 

Luca

**Comment by Hugo-ter-Doest** [comment]
Fixed it. Thanks for the heads up!
