### ISSUE TITLE
Version 0.5.7 is not published

### ISSUE THREAD

**Issue by sospedra** [NaturalNode/natural#433]
https://www.npmjs.com/package/natural?activeTab=versions

No `SentimentAnalyzer` :(

**Comment by Hugo-ter-Doest** [comment]
Yes, I know. One of the owners has to publish a new version to NPM. I can't do it. For the time being you can clone the package from Github and then use it.

Hugo

**Comment by Hugo-ter-Doest** [comment]
Version 0.6.0 has been published on NPM.

Hugo
