### ISSUE TITLE
Testing browser support

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [NaturalNode/natural#434]
I was reading some issues about browser support which I think it is an important feature to have. So I'm considering to add support for testing natural in a browser setting. My question is whether it would make sense to run the test suite (consisting of a collection of jasmine tests) with a test sequence using [Browserify](http://browserify.org/) (or [Webpack](https://webpack.js.org/)) and [PhantomJS](http://phantomjs.org/). This way we can make sure that natural works in the browser. Also, we could require pull requests/commits to successfully run in a browser environment. Please let me know your ideas and suggestions.

Hugo

**Comment by aolney** [comment]
I've got brill tagging working in the browser using [browserfs](https://github.com/jvilk/BrowserFS) with webpack. The only thing I needed to do to `natural` for this was to pull the model files into a zip and then `fetch` it. `browserfs` has shims for all the node calls like `fs`.

**Comment by Hugo-ter-Doest** [comment]
I refactored most of the <code>fs</code> dependencies to require's with <code>JSON</code> files. For writing files, like for classifiers, you still need <code>fs</code>, for everything else <code>require</code> is used. Also, most <code>require</code> statements are with hard paths, so no expressions. Webpack has problems with that as well.

I think this solves most of the problems with the use in browsers.

I also included a Gulp/Webpack configuration that tests most jasmine specs in the browser. 

I will close this issue now, but please comment or open new issues for more and better browser support.

**Comment by aolney** [comment]
I was a little confused at first because the signatures changed for creating a lexicon and ruleset, but after I looked at the new code it was clear. As expected, those were the only changes I needed to make for things to work.

**Comment by Hugo-ter-Doest** [comment]
I'm sorry for the breaking changes. Also, I still need to update the README.

**Comment by aolney** [comment]
No probs, thanks for all your efforts :+1:
