### ISSUE TITLE
Use safe dependency version ranges

### ISSUE THREAD

**Issue by gajus** [NaturalNode/natural#435]
The current dependency version ranges allow breaking changes:

https://github.com/NaturalNode/natural/blob/2ad8d67197f57c6759f5c9753a54d9cf396a9cdf/package.json#L13-L25

You cannot use `>=` because that will allow major changes.

It should be:

```json
"dependencies": {
  "afinn-165": "^1.0.2",
  "apparatus": "^0.0.9",
  "json-stable-stringify": "^1.0.1",
  "sylvester": "^0.0.12",
  "underscore": "^1.3.1"
},
"devDependencies": {
  "jasmine-node": "^1.13.1",
  "proxyquire": "^1.8.0",
  "sinon": "^1.12.2",
  "uubench": "^0.0.0"
},

```

And remove `package-lock.json` file from the source-control.

`package-lock.json` is designed for program authoring, not package authoring.

If your source control contains `package-lock.json` then your CI jobs may be run against different version of dependencies then the projects that depend on natural will be resolve based on Natural `package.json` (remember: `package-lock.json` is not committed to NPM).

**Comment by Hugo-ter-Doest** [comment]
Ok, thanks! Will commit these changes later today.

Hugo

**Comment by gajus** [comment]
Ignore the:

> And remove package-lock.json file from the source-control.

There is a bit of controversy about this issue.

https://github.com/npm/npm/issues/20603

Whether to keep `package-lock.json` is subjective.

**Comment by Hugo-ter-Doest** [comment]
See PR [#436](https://github.com/NaturalNode/natural/pull/436)
