### ISSUE TITLE
SentenceTokenizer destroying some punctuation

### ISSUE THREAD

**Issue by giorgio79** [NaturalNode/natural#437]
Test example:

```
var natural = require('natural');
var tokenizer = new natural.SentenceTokenizer();
console.log(tokenizer.tokenize("I love you!! Do you love me??"));
```
Result
[ 'I love you!', 'Do you love me?' ]

**Comment by Hugo-ter-Doest** [comment]
You are right. The regular expression allows for only one punctuation symbol together:
```

**Comment by Hugo-ter-Doest** [comment]
Repaired with PR [#440](https://github.com/NaturalNode/natural/pull/440)
