### ISSUE TITLE
Jaro-Winkler Distance Algorithm Match Value Question

### ISSUE THREAD

**Issue by DamonOehlman** [NaturalNode/natural#44]
Firstly, a massive thank-you for putting this library together.  It's been really helpful implementing some text similarity behaviour in an application I'm currently writing. 

Secondly, I just wanted to ask a question regarding the match value that is returned from the `JaroWinklerDistance` algorithm.  On reading the [wikipedia article](http://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance) I definitely got the impression that a comparison between two strings that are exactly the same should return a result of 1.  I'm finding, however, that this isn't the case.

In the application I'm currently writing, I'm using the functionality to order place names in order of their match strength against an original request.  In the case of sydney, this works as expected:

```
> natural.JaroWinklerDistance('sydney', 'sydney');
1
```

However, when I did a comparison for seddon against seddon, it returns less than 1:

```
> natural.JaroWinklerDistance('seddon', 'seddon');
0.8933333333333334
```

I went on to do some other smaller tests in the node console to see if I could have the function produce a higher score for two different strings than two that were exactly the same, as realistically, this is the case that I'm worried might occur.  After a little bit of playing around I found that I could:

```
> natural.JaroWinklerDistance('abc', 'abc');
0.8666666666666666
> natural.JaroWinklerDistance('abcd', 'abcd');
1
> natural.JaroWinklerDistance('abcd', 'abc');
0.9416666666666667
```

Once I grok the algorithm, I'll have a look at forking the code and seeing if I can work out where this is happening, but I thought I'd raise an issue first to see if it was something that someone else knew how to fix quickly and simply.

Thanks again for your efforts on the library.

Cheers,
Damon.

**Comment by shieee** [comment]
Hi,

I would like to ask about JaroWinklerDistance algorithm. 

My team made a comparison between 'jezze' and '09270000000' and it returned 0.411111111111111 value (we are expecting 0).
 
To be honest I am not familiar with Jaro-Winkler and it's algorithm, but upon researching about it I found out that Jaro-Winkler is really useful. My question is, maybe the implementation of the algorithm is incorrect?

Hoping for your feedback.

Thank you!

**Comment by adamb0mb** [comment]
You are correct, this should be 0.

**Comment by Hugo-ter-Doest** [comment]
I tested this, and works like expected. See #491 for the same issue and my answer.

**Comment by adamb0mb** [comment]
👍. Thanks

That was my next step, but haven't pulled this repo on years.
