### ISSUE TITLE
How to use customized tokenizer in classifier ?

### ISSUE THREAD

**Issue by ahkimkoo** [NaturalNode/natural#441]
How to use customized tokenizer in classifier and tf-idf, I have Chinese tokenizer but how to replace default tokenizer to my tokenizer.

**Comment by Hugo-ter-Doest** [comment]
You can pass a stemmer to the constructor of a classifier: https://github.com/NaturalNode/natural/blob/b05a271fd446e837ebaedf35eb634f3fcc3cffa4/lib/natural/classifiers/classifier.js#L41

The classifier assumes that the stemmer takes care of tokenization: see for instance https://github.com/NaturalNode/natural/blob/b05a271fd446e837ebaedf35eb634f3fcc3cffa4/lib/natural/classifiers/classifier.js#L61
So, if you want to use the classifier for Chinese, you could define a stemmer/tokenizer and pass it to the classifier. It should support `tokenizeAndStem` as a method.

Hugo

**Comment by Hugo-ter-Doest** [comment]
Regarding tfidf you have to edit the code `tfidf.js` to change the default tokenizer. See https://github.com/NaturalNode/natural/blob/b05a271fd446e837ebaedf35eb634f3fcc3cffa4/lib/natural/tfidf/tfidf.js#L24

Just change the tokenizer to your own, but take care of the API of the tokenizer: tfsidf expects `tokenize` as a method.

Hugo
