### ISSUE TITLE
change default word-splitting regex in WordTokenizer or add an option to ngrams to be able to set regex for Tokenizers.WordTokenizer

### ISSUE THREAD

**Issue by lury** [NaturalNode/natural#456]
I'm using ngrams function and i don't get why do you use this regex as a default to split words?
https://github.com/NaturalNode/natural/blob/73acfeb3527ba4091f821759d056ac83d01ffe71/lib/natural/tokenizers/regexp_tokenizer.js#L85

It is useless for polish language (and many others) since we have following chars with accents: 
ąśżźćńóę 
and expanding this regex doesn't seem like a fix.

this regex in my opinion should be something like:

``` /[.!?\s]+/```

so we have an inclusive list of word breaking/ending characters, rather than exclusion of partial set of chars which are allowed in words.

I'm not saying that my char list is complete but i don't get the approach used here.
If it'd be as proposed, ngrams would work for all languages, while now i basically have to add my own ngram_pl.js just to pass proper regex to Tokenizer.

## Other solution
Since regexTokenizer has an option to set regex used to split words, another solution would be to add regex as an option to the ngram function and pass it along the way when instantiating default Tokenizer.
It doesn't look like it's possible right now - i mean i've tried to use setTokenizer() but i'd have to hardcode path to your regexp tokenizer simply to call Tokenizer constructor with `pattern` param...
 
P.S.
XRegExp seems like an overkill here.
P.P.S.
following solutions from SO like this one yields no satisfying results: https://stackoverflow.com/questions/20690499/concrete-javascript-regex-for-accented-characters-diacritics

**Comment by Hugo-ter-Doest** [comment]
The regexp_tokenizer can be used in two ways: you can split on gaps or by giving a pattern for words. So, for Polish you can create a regexp_tokenizer by passing gaps in the options.
```javascript
tokenizer = new natural.RegexpTokenizer({pattern: /.!?\s/});
```

AND I think there is a bug in the regexp_tokenizer:
```javascript
RegexpTokenizer.prototype.tokenize = function(s) {
    var results;

    if (this._gaps) {
        results = s.split(this._pattern);
        return (this.discardEmpty) ? _.without(results,'',' ') : results;
    } else {
        return s.match(this._pattern);
    }
};
```
If `this._gaps` has a value it used the `this._pattern` to split. That is wrong. 

I will look into this in the weekend.

Hugo

**Comment by lury** [comment]
ok but how can i pass it when i'm using ngrams function? i know that i can set up custom tokenizer when i only want to use tokenizer, but the issue is that i can't do this when using ngrams feature because it's packed in a way that there is no way to pass this custom setup.

I'm talking about this line:
https://github.com/NaturalNode/natural/blob/master/lib/natural/ngrams/ngrams.js#L25

**Comment by Hugo-ter-Doest** [comment]
You can use `setTokenizer` to pass your own tokenizer to ngrams. See line
https://github.com/NaturalNode/natural/blob/73acfeb3527ba4091f821759d056ac83d01ffe71/lib/natural/ngrams/ngrams.js#L29
