### ISSUE TITLE
The Sentiment Analysis example fails

### ISSUE THREAD

**Issue by terrarum** [NaturalNode/natural#462]
If I run the Sentiment Analysis example I get this error:

```
TypeError: words.forEach is not a function
    at SentimentAnalyzer.getSentiment (/Users/fidlejw7/Development/localhost/matchmaker/node_modules/natural/lib/natural/sentiment/SentimentAnalyzer.js:84:11)
```

If I log `words` in `SentimentAnalyzer.js` it's coming through as a string rather than an array.

**Comment by terrarum** [comment]
Ah, you're meant to pass in an array of words, so I guess the example just needs updating!

**Comment by Hugo-ter-Doest** [comment]
> Ah, you're meant to pass in an array of words, so I guess the example just needs updating!

I tested the example and it works just fine. It uses arrays like you say:
```
var Analyzer = require('natural').SentimentAnalyzer;
var stemmer = require('natural').PorterStemmer;
var analyzer = new Analyzer("English", stemmer, "afinn");
// getSentiment expects an array of strings
console.log(analyzer.getSentiment(["I", "like", "cherries"]));
// 0.6666666666666666
```

**Comment by terrarum** [comment]
I swear I copied it directly but the git history proves me a liar. I must have changed it myself and forgot! Sorry, and thanks!
