### ISSUE TITLE
Warnings when using natural in larger project

### ISSUE THREAD

**Issue by dsl101** [NaturalNode/natural#470]
I'm using `natural` in a larger Vue-based project, and after installing it I see the following 4 warnings emitted when I build the project:
```
 WARNING  Compiled with 4 warnings                                                                                                                 12:24:52 PM

 warning  in ./node_modules/natural/lib/natural/sentiment/SentimentAnalyzer.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/natural/lib/natural/sentiment/SentimentAnalyzer.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/natural/lib/natural/classifiers/classifier.js

Module not found: Error: Can't resolve 'webworker-threads' in '...\Vue\Quasar\Feedfilter\node_modules\natural\lib\natural\classifiers'

 warning  in ./node_modules/natural/lib/natural/wordnet/wordnet.js

Module not found: Error: Can't resolve 'wordnet-db' in '...\Vue\Quasar\Feedfilter\node_modules\natural\lib\natural\wordnet'
```

Did I miss something in the installation / setup?

**Comment by dsl101** [comment]
I've edited the title of this issue to be more specific. The warning is coming from Webpack, and it's lines 49 and 66 in SentimentAnalyzer.js, which use a dynamic `require()`. This is problematic for Webpack, as documented [here](https://webpack.js.org/guides/dependency-management/#require-with-expression), but I don't know how that can be fixed since the 'natural' library doesn't explicitly use Webpack.

**Comment by Hugo-ter-Doest** [comment]
We could require all modules statically in advance. This means that for instance
```
    "Spanish": ["./Spanish/senticon_es.json", "./Spanish/negations_es.json"],
````
is replaced by 
```
const spanishScores = require("./Spanish/senticon_es.json");
const spanishNegations = require("./Spanish/negations_es.json");

    "Spanish": [spanishNegation, spanishScores],
```
This way there are no dynamic requires. The downside is that all files are included beforehand.

**Comment by dsl101** [comment]
Hmm. Does webpack shake that particular tree though? Perhaps Natural would need a version for dynamic loading, and version for use with webpack, to avoid the worst of both worlds?

I'm afraid I don't know enough about webpack to understand how it computes what is actually used, and whether that can even be statically determined, but providing the language in use isn't also an expression, I _think_ webpack can figure out what needs to be included in the bundle. I've seen articles like [this one](https://medium.com/front-end-hacking/webpack-and-dynamic-imports-doing-it-right-72549ff49234) but since I'm not using webpack directly (I'm building a Vue-based app, so webpack is part of the Vue tooling), a lot of that passes me by...

**Comment by Berkmann18** [comment]
I've got the same error after trying to use this in VueJS.

**Comment by Hugo-ter-Doest** [comment]
I think this should work since we test specs in the browser
