### ISSUE TITLE
Add "christmas" to inflector ambiguous words

### ISSUE THREAD

**Issue by rawpixel-vincent** [NaturalNode/natural#476]
Follow up for the PR https://github.com/NaturalNode/natural/pull/475

**Comment by rawpixel-vincent** [comment]
I'm actually not sure, it should be there... Its a proper noun right.. 
So better use wordpos ?

**Comment by Hugo-ter-Doest** [comment]
As I understand it, the list of ambiguous words cannot be pluralized. This holds for christmas as far as I know. Merged the PR. Thanks!
