### ISSUE TITLE
SentenceTokenizer chopping off last word if end of sentence punctuation is missing

### ISSUE THREAD

**Issue by giorgio79** [NaturalNode/natural#480]
https://runkit.com/giorgio79/5c0fc754d5c9530012e8b978
```
var natural = require("natural")
tokenizer = new natural.SentenceTokenizer();
var sentences = tokenizer.tokenize("Just testing this natural");
```
Gives "Just testing this"

![image](https://user-images.githubusercontent.com/283347/49806542-4d433680-fd58-11e8-9920-0670e429a561.png)

**Comment by aolney** [comment]
Replicated. Work around seems to be to right pad text with one space, e.g. `"Just testing this natural "`

**Comment by Hugo-ter-Doest** [comment]
Repaired with #488
