### ISSUE TITLE
Jaro-Winkler Algorithm Match Value Question

### ISSUE THREAD

**Issue by shieee** [NaturalNode/natural#491]
Hi,

I would like to ask about JaroWinklerDistance algorithm.

My team made a comparison between 'jezze' and '09270000000' and it returned 0.411111111111111 value (we are expecting 0).

To be honest I am not familiar with Jaro-Winkler and it's algorithm, but upon researching about it I found out that Jaro-Winkler is really useful. My question is, maybe the implementation of the algorithm is incorrect?

Hoping for your feedback.

Thank you!

**Comment by Hugo-ter-Doest** [comment]
I added the following test to `spec/jaro-winkler_spec.js`:

```
it('should process strings with 0 matches', function() {
      expect(jaroWinklerDistance('jezze', '09270000000')).toEqual(0);
    });
```

And it results in 0 like expected. Please post your code here so I can take a look.
