### ISSUE TITLE
NPM not up-to-date

### ISSUE THREAD

**Issue by dhruv-tech** [NaturalNode/natural#495]
Hello, was trying to use BrillPOSTagger on my npm installation of Natural based on the documentation provided on GitHub and I realized that the npm version of Natural doesn't seem to be updated (refer to the POS Tagger part of the documentation on GitHub and npm). Request you to ensure that updates are published regularly to npm as well.

**Comment by Hugo-ter-Doest** [comment]
I think the version on NPM is up-to-date with the one here. Maybe one commit behind, but that did not touch the Brill tagger. Can you elaborate on what went wrong?

**Comment by dhruv-tech** [comment]
Please look at the documentation on GitHub for POS tagger and compare it with what we have on NPM, they are not identical. Moreover, the example given on the GitHub version of the documentation does not work with the npm installation.

**Comment by Hugo-ter-Doest** [comment]
Published new version(s) to NPM
