### ISSUE TITLE
What can tfidf.idf method be used for?

### ISSUE THREAD

**Issue by monks1975** [NaturalNode/natural#496]
I'm looking to filter out tokens that are frequent across all classes, as part of feature selection for a bayes classifier. Can I use what is returned from tfidf.idf for this?

**Comment by Hugo-ter-Doest** [comment]
TF-IDF ranks tokens highly that are frequent in a document but not in the total collection of documents. TF-IDF is a function of (token, document, document collection). Terms with a low TF-IDF ranking are considered not very  informative, or discriminative. I expect that this may work to select tokens for feature selection. But you can check the improvement of your classifier with and without applying TF-IDF for feature selection.
