### ISSUE TITLE
SentenceTokenizer does not properly handle Inc. and etc

### ISSUE THREAD

**Issue by servel333** [NaturalNode/natural#497]
### To reproduce

```
const natural = require('natural');
const tokenizer = new natural.SentenceTokenizer();
const phrase = "Acme, Inc. is creating exciting products. Use at you're own risk.";
console.log(JSON.stringify(tokenizer.tokenize(phrase)));
```

### Actual results

```
["Acme, Inc.","is creating exciting products.","Use at you're own risk."]
```

### Expected results

```
["Acme, Inc. is creating exciting products.","Use at you're own risk."]
```

**Comment by Hugo-ter-Doest** [comment]
I see...the problem here is that the tokenizer only takes into account punctuation characters and does not have any knowledge about abbreviations. I'm not sure if we can/should try to repair this.

**Comment by servel333** [comment]
It's fair if it's a "won't fix", I just noticed this and figured I would point it out. Thanks.

**Comment by Hugo-ter-Doest** [comment]
Added support for abbreviations to the parser-based sentence tokenizer.
