### ISSUE TITLE
tokenizeAndStem()  is not stemming words as expected 

### ISSUE THREAD

**Issue by ElectroP** [NaturalNode/natural#498]
var natural = require('natural');
var stemmer = require('stemmer')
console.log("The Road is one of the great fundamental institutions of mankind.".tokenizeAndStem());

output:[ 'road', 'on', 'great', 'fundament', **'institut',** 'mankind' ]
Expected op: [ 'road', 'on', 'great', 'fundament', **'institute',** 'mankind' ]

it is omitting some letters

**Comment by coyotte508** [comment]
I think it's normal, "insitut" is the stem.

**Comment by Hugo-ter-Doest** [comment]
The stem of a word is not necessarily a word that you find in a dictionary.
