### ISSUE TITLE
noun inflector: add -f / -fe to -ves rules and exceptions

### ISSUE THREAD

**Issue by rawpixel-vincent** [NaturalNode/natural#500]
The -f / -fe to -ves rule can be handled but with many exceptions that need to be explicitely set.

1. Words ending in -ff or -ffe you just add s to make the plural.
Sheriffs | Giraffes

2. words ending in f that just add s:
roof - roofs
chief - chiefs
oaf -oafs

3. Example of words using the -f / -fe to -ves rule
leaf - leaves
wolf - wolves
calf - calves
half - halves
knife - knives
loaf - loaves
life - lives
wife - wives
shelf - shelves
thief - thieves
yourself - yourselves

4. Some words have multiple valid plural forms endings with -ves or -s:
scarf - scarfs/scarves
dwarf - dwarfs / dwarves
wharf - wharfs / wharves
handkerchief - handkerchiefs / handkerchieves

**Comment by Hugo-ter-Doest** [comment]
See PR #593.

> 1. Words ending in -ff or -ffe you just add s to make the plural.
> Sheriffs | Giraffes

Both singularisation and pluralisation already work with the current inflector. 

> 2. words ending in f that just add s:
> roof - roofs
> chief - chiefs
> oaf -oafs

Both singularisation and pluralisation already work with the current inflector. 

> 3. Example of words using the -f / -fe to -ves rule
> leaf - leaves
> wolf - wolves
> calf - calves
> half - halves
> knife - knives
> loaf - loaves
> life - lives
> wife - wives
> shelf - shelves
> thief - thieves
> yourself - yourselves

Added as irregular forms.

> 4. Some words have multiple valid plural forms endings with -ves or -s:
> scarf - scarfs/scarves
> dwarf - dwarfs / dwarves
> wharf - wharfs / wharves
> handkerchief - handkerchiefs / handkerchieves

Added the cases with `ves` to the singularisation.

All cases were added to the test file.
