### ISSUE TITLE
PorterStemmerFr and stopwords that begin a sentence

### ISSUE THREAD

**Issue by coyotte508** [NaturalNode/natural#502]
For example:

```
// Returns ['j', 'aim']
natural.PorterStemmerFr.tokenizeAndStem("J'aime");

// Returns ['aim']
natural.PorterStemmerFr.tokenizeAndStem("j'aime");
```

In both cases the return value should just be `['aim']`.

I think it's because the lowercase is applied *after* stopwords are removed, and not before.

**Comment by Hugo-ter-Doest** [comment]
Thanks! Changed the order: first convert the token to lowercase, then match against stop words.
https://github.com/NaturalNode/natural/pull/530
