### ISSUE TITLE
New version release info

### ISSUE THREAD

**Issue by vinayuttam** [NaturalNode/natural#503]
It's been over 10 months since the last release. Can we when the next version would be released?

**Comment by kwasimensah** [comment]
Note, the documentation around POS Tagger is now out of date on Github (Github and source code use 'EN' and 'DU" tags while the published 0.6.3 version requires putting together a filepath).

**Comment by OmarJay1** [comment]
Is there a workaround for the 'EN' error?  When I try the POS tagger example, the RuleSet seems to give an error.  Thanks.

var ruleSet = new natural.RuleSet('EN');

>>>>>>

{ Error: ENOENT: no such file or directory, open 'EN'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at new Lexicon (C:\omni\Node\vmaud\server\node_modules\natural\lib\natural\brill_pos_tagger\lib\Lexicon.js:29:21)
...

**Comment by Hugo-ter-Doest** [comment]
I will push a new version to NPM soon now.

**Comment by Hugo-ter-Doest** [comment]
Pushed a new version to NPM. It is a major release to 1.0.0 because of breaking changes in the use of external files.
