### ISSUE TITLE
Getting default category for all tokens in POS tagger

### ISSUE THREAD

**Issue by francoguilherme** [NaturalNode/natural#507]
Hello,
I followed the exact instructions for the Brill POS Tagger in the README but I'm getting 'N' tags for all the tokens. What am I doing wrong? Do I need to train it?

**Comment by alexabruck** [comment]
Do you also get the ENOENT error? Then this might be the same issue: https://github.com/NaturalNode/natural/issues/518

**Comment by Hugo-ter-Doest** [comment]
Please post your code, so I can have a look. I did not experience any problems, maybe it has something to do with search path.

**Comment by Hugo-ter-Doest** [comment]
This is caused by a version mismatch between NPM and Github. I upgraded the version on NPM.
