### ISSUE TITLE
N-API version of Damerau-Levenshtein

### ISSUE THREAD

**Issue by haggholm** [NaturalNode/natural#513]
No action suggested here; I just wanted to let you know that I’ve ported your implementation of Damerau-Levenshtein string distance through a rather literal translation into N-API/C++. Feel free to use it or ignore it as you see fit.

https://github.com/haggholm/damerau-levenshtein

**Comment by Hugo-ter-Doest** [comment]
Thanks for your work. I'm impressed by the performance improvement!
