### ISSUE TITLE
POSTagger Error: ENOENT: no such file or directory, open 'EN'

### ISSUE THREAD

**Issue by alexabruck** [NaturalNode/natural#518]
I basically copied the code from the README section about POSTagging (https://github.com/NaturalNode/natural#pos-tagger).

This throws an ENOENT error and also, confusingly, returns the (uninformed) tagged result (e.g. everything is NN).

It seems that the first argument of the Lexicon constructor is expecting a filename.

**Comment by ezhou7** [comment]
Came across same issue. NPM latest package version is not up-to-date with GitHub repo code. If you're using Yarn package manager, use this command:

`yarn add https://github.com/NaturalNode/natural`

If you're using NPM, use this command:

`npm install https://github.com/NaturalNode/natural`

Should give you the latest code. Hope this helps.

**Comment by Hugo-ter-Doest** [comment]
I installed natural using NPM and executed the following code from the README:
```
var natural = require("natural");
const language = "EN"
const defaultCategory = 'N';
const defaultCategoryCapitalized = 'NNP';

var lexicon = new natural.Lexicon(language, defaultCategory, defaultCategoryCapitalized);
var ruleSet = new natural.RuleSet('EN');
var tagger = new natural.BrillPOSTagger(lexicon, ruleSet);

var ruleSet = new natural.RuleSet('EN');

var tagger = new natural.BrillPOSTagger(lexicon, ruleSet);
var sentence = ["I", "see", "the", "man", "with", "the", "telescope"];
console.log(tagger.tag(sentence));
```
and had no problems...

Could you please post your code, so I can take a look?

**Comment by alexabruck** [comment]
@Hugo-ter-Doest 
I literally copied the code from the README:
```
var natural = require("natural");
const language = "EN";
const defaultCategory = "N";
const defaultCategoryCapitalized = "NNP";

var lexicon = new natural.Lexicon(
  language,
  defaultCategory,
  defaultCategoryCapitalized
);
var ruleSet = new natural.RuleSet("EN");
var tagger = new natural.BrillPOSTagger(lexicon, ruleSet);
var sentence = ["I", "see", "the", "man", "with", "the", "telescope"];
console.log(tagger.tag(sentence));
```
which logs to the console
```
Sentence {
  taggedWords:
   [ { token: 'I', tag: 'NNP' },
     { token: 'see', tag: 'N' },
     { token: 'the', tag: 'N' },
     { token: 'man', tag: 'N' },
     { token: 'with', tag: 'N' },
     { token: 'the', tag: 'N' },
     { token: 'telescope', tag: 'N' } ] }
```
Before, it prints the ENOENT error message to the console.

**Comment by alexabruck** [comment]
@ezhou7 is correct: The package on NPM is not up to date. Fetching from Github works without problems.

**Comment by Hugo-ter-Doest** [comment]
@alexabruck I don't have the problem, neither with the NPM version or with the version from the repo. Which version of node are you using? On which OS are you working. I'm thinking of problems with require and search paths.

**Comment by alexabruck** [comment]
@Hugo-ter-Doest 
Node Version: 11
OS: macOS 10.14.6

**Comment by ezhou7** [comment]
@Hugo-ter-Doest there is a discrepancy b/w the code on GitHub and the code from NPM.
Code from GitHub for initializing new `Lexicon` object in `Lexicon.js`:
```
function Lexicon(language, defaultCategory, defaultCategoryCapitalised) {
  switch (language) {
    case 'EN':
      this.lexicon = englishLexicon;
      break;
    case 'DU':
      this.lexicon = dutchLexicon;
      break;
    default:
      this.lexicon = dutchLexicon;
      break;
  }
  if (defaultCategory) {
    this.defaultCategory = defaultCategory;
    if (defaultCategoryCapitalised) {
      this.defaultCategoryCapitalised = defaultCategoryCapitalised;
    }
  }
}
```

Code from NPM for initializing new `Lexicon` object in `Lexicon.js` (from v0.6.3 - https://npm.runkit.com/natural/lib/natural/brill_pos_tagger/lib/Lexicon.js):
```
function Lexicon(filename, defaultCategory, defaultCategoryCapitalised) {
  this.lexicon = {}; //Object.create(null);
  if (filename) {
    this.defaultCategory = defaultCategory;
    // Read lexicon
    try {
      var data = fs.readFileSync(filename, 'utf8');
      if (data[0] === "{") {
        // Lexicon is in JSON format
        this.lexicon = JSON.parse(data);
      }
      else {
        // Lexicon is plain text
        this.parseLexicon(data);
      }
      //console.log('Brill_POS_Tagger.read_lexicon: number of lexicon entries read: ' + Object.keys(this.lexicon).length);
    }
    catch (error) {
      console.error(error);
    }
    if (defaultCategory) {
      this.defaultCategory = defaultCategory;
      if (defaultCategoryCapitalised) {
        this.defaultCategoryCapitalised = defaultCategoryCapitalised;
      }
    }
  }
}
```

That's probably why there's an `ENOENT` issue since the NPM package still requires an actual filename and the GitHub code requires just a language string (e.g. "EN", "DU", etc.).

Hope this helps.

**Comment by Hugo-ter-Doest** [comment]
Pushed a new version to NPM. It is a major release to 1.0.0 because of breaking changes in the use of external files.
