### ISSUE TITLE
Address Search

### ISSUE THREAD

**Issue by scriptsure** [NaturalNode/natural#519]
Sorry to ask this question here but i suspect it will take someone all of 2 seconds to give me an answer. I see a lot of single sentence examples but none where there are large sets of data....

I have a list of 70,000 addresses that i need to be able to search through that are stored in a MySql database. I want to use natural to perform searches probably using string distance to determine if the address is a match to show user. Some of the use cases are where they spell it wrong or where they have abbreviated (i.e. Ave vs Avenue, St. vs Saint, Altanta vs Atlanta). Additionally, after it is found i need to return the identification code for the address, so that it may be used on UI... If the user selects the address the code will be used for downstream processing.

How do i load all 70,000 into memory like that so that natural can search all 70,000? Is this dangerous loading so much data into memory.... 

I guess I am lost as to how you search large datasets like this... particularly when they are stored in a database.?

**Comment by Hugo-ter-Doest** [comment]
I think you are looking for an autocomplete solution for addresses. Which is not functionality of natural...

**Comment by scriptsure** [comment]
@Hugo-ter-Doest no that is not my question... the question is using naturaljs what is the best approach to searching through large datasets?
