### ISSUE TITLE
[performance issue] `classifier.train()` is very slow - and `classifier.trainParallel()` is no longer available - what are the alternatives for optimization while training?

### ISSUE THREAD

**Issue by niftylettuce** [NaturalNode/natural#520]
Since `webworker-threads` seems to have been deprecated, I'm curious what the new recommended approach is?

I also wanted to point out that `trainParallel` is not documented at all in the README.

**Comment by niftylettuce** [comment]
I am using <https://github.com/surmon-china/naivebayes> as an alternative since this package's bayesian classifier is not production-ready

**Comment by Hugo-ter-Doest** [comment]
`webworker-threads` can be used but are optional. If the module is installed it will be used. In `classifier.js`:

```
try {
    var Threads = require('webworker-threads');
} catch (e) {
    // Since webworker-threads are optional, only thow if the module is found
    if (e.code !== 'MODULE_NOT_FOUND') throw e;
}
```
