### ISSUE TITLE
Loads not requested Indonesian stemmer and ja normalizers

### ISSUE THREAD

**Issue by crystalfp** [NaturalNode/natural#524]
Profiling my node application, I noticed the following lines:
```
      1   50.0%          LazyCompile: ~loadDictionary ...\node_modules\natural\lib\natural\stemmers\indonesian\stemmer_id.js:129:24
      1  100.0%            Eval: ~<anonymous> ...\node_modules\natural\lib\natural\stemmers\indonesian\stemmer_id.js:1:1
      1   50.0%          LazyCompile: ~loadDictionary ...\node_modules\natural\lib\natural\stemmers\indonesian\prefix_rules.js:31:24
      1  100.0%            Eval: ~<anonymous> ...\node_modules\natural\lib\natural\stemmers\indonesian\prefix_rules.js:1:1
      1    4.2%        LazyCompile: ~replacer ...\node_modules\natural\lib\natural\util\utils.js:33:18
      1  100.0%          Eval: ~<anonymous> ...\node_modules\natural\lib\natural\normalizers\normalizer_ja.js:1:1
```
My `natural` usage is very simple (typescript code):
```
import {PorterStemmerIt, PorterStemmer} from "natural";
const stword = (language === "it") ? PorterStemmerIt.stem(word) : PorterStemmer.stem(word);
```
My words are only in English or Italian.
Why the references to Indonesian stemmer and the Japanese normalizer?
I'm doing anything wrong with stemmer usage?
Thanks for your help!
mario

natural: 1.0.1
node 12.16.1
os: Windows 10 64 bits

**Comment by Hugo-ter-Doest** [comment]
I don't know. I checked for dependencies in the stemmers for English and Italian, and did not find any so far. Strangely, both the Japanese stemmer (which used a normalizer for Japanese) and the Indonesian stemmer have an implementation that deviates from the Porter stemmers.

**Comment by crystalfp** [comment]
I retried with a larger, different corpus and it does not happen anymore. The problem is probably an artifact of the profiler sampling. Sorry for the noise.
mario
