### ISSUE TITLE
Strange return from attached stemmer

### ISSUE THREAD

**Issue by crystalfp** [NaturalNode/natural#525]
Found a very strange behavior of attached stemmers. It happens only with two letters words:
```
const natural = require("natural")
undefined
> natural.PorterStemmer.attach()
undefined
> "going".stem()
'go'
> "yi".stem()
[String: 'yi']
> typeof "yi".stem()
'object'
>
```
The strange behavior could be circumvented by adding a call to `toString()`:
```
"yi".stem().toString()`
'yi'
```
Apart from this strangeness, typescript complains strongly that `stem()` is not found on string type.

Unfortunately all this makes the interesting `attach()` idea pretty unusable.

Thanks for clarifying!
mario

natural: 1.0.1

**Comment by Hugo-ter-Doest** [comment]
I think I found the problem in `porter_stemmer.js`:

```
PorterStemmer.stem = function(token) {
    if(token.length < 3) return token;
    return step5b(step5a(step4(step3(step2(step1c(step1b(step1a(token.toLowerCase())))))))).toString();
};
```

This means that the string object is returned for strings of length 2 and less. To make sure a string is returned I will change it to:
```
PorterStemmer.stem = function(token) {
    if(token.length < 3) return token.toString();
    return step5b(step5a(step4(step3(step2(step1c(step1b(step1a(token.toLowerCase())))))))).toString();
};
```

**Comment by Hugo-ter-Doest** [comment]
See https://github.com/NaturalNode/natural/pull/528
