### ISSUE TITLE
Issue resolving 'afinnShortSortedSpanish' in Sentiment Analyzer

### ISSUE THREAD

**Issue by ezhou7** [NaturalNode/natural#526]
Hi there,

I've come across an error when using the `natural` package:
```
ERROR in ./node_modules/natural/lib/natural/sentiment/SentimentAnalyzer.js
Module not found: Error: Can't resolve './Spanish/afinnShortSortedSpanish' in '/Users/ezhou7/VSCodeProjects/synesthesis/node_modules/natural/lib/natural/sentiment'
 @ ./node_modules/natural/lib/natural/sentiment/SentimentAnalyzer.js 25:25-69
 @ ./node_modules/natural/lib/natural/index.js
 @ ./src/app/pages/Editor/english.ts
 @ ./src/app/pages/Editor/index.tsx
 @ ./src/app/index.tsx
```

It looks like there's a mistake in `SentimentAnalyzer.js` on line 25 (https://github.com/NaturalNode/natural/blob/master/lib/natural/sentiment/SentimentAnalyzer.js#L25).

`const spanishAfinnVoca = require("./Spanish/afinnShortSortedSpanish")`
should be
`const spanishAfinnVoca = require("./Spanish/afinnShortSortedSpanish.json")`.

Thanks!

**Comment by Hugo-ter-Doest** [comment]
Thanks! See https://github.com/NaturalNode/natural/pull/527 for the repair.
