### ISSUE TITLE
TypeError: Cannot read property 'without' of undefined

### ISSUE THREAD

**Issue by sjain3097** [NaturalNode/natural#538]
TypeError: Cannot read property 'without' of undefined
WordTokenizer.push../node_modules/natural/lib/natural/tokenizers/regexp_tokenizer.js.RegexpTokenizer.tokenize
E:/react dir/chatbot/nlp/nlp-trial/node_modules/natural/lib/natural/tokenizers/regexp_tokenizer.js:48
  45 | 
  46 | if (this._gaps) {
  47 |     results = s.split(this._pattern);
> 48 |     return (this.discardEmpty) ? _.without(results,'',' ') : results;
     | ^  49 | } else {
  50 |     return s.match(this._pattern);
  51 | }

**Comment by sjain3097** [comment]
i am trying to use tokenizer in react.js but this error pops up

**Comment by Hugo-ter-Doest** [comment]
So, I see this is still an issue. I hoped I fixed it.

**Comment by Hugo-ter-Doest** [comment]
It has a relation with react, that is for sure. Any clues what is going on?

**Comment by sjain3097** [comment]
no idea i am new to react so i was hoping someone here can help me

**Comment by sjain3097** [comment]
all i can think is for some reason react is not able to use underscore and thus giving it undefined

**Comment by Hugo-ter-Doest** [comment]
Something went wrong with publishing to NPM. Please try again.

**Comment by sjain3097** [comment]
i will try installing again

**Comment by sjain3097** [comment]
working now

**Comment by sjain3097** [comment]
thanks man
