### ISSUE TITLE
how can i train my nlp for questions such as "who are you?" because all of these are considered stop words this an empty stem array is passed by default  

### ISSUE THREAD

**Issue by sjain3097** [NaturalNode/natural#539]

**Comment by NotABlueWhale** [comment]
For reference, you can disable stop word removal on a classifier as follows:

`var classifier = new natural.BayesClassifier();
classifier.setOptions({ keepStops: true })`

**Comment by Hugo-ter-Doest** [comment]
@NotABlueWhale thanks
