### ISSUE TITLE
Search an array of tokens in a text file.

### ISSUE THREAD

**Issue by chainhead** [NaturalNode/natural#545]
I have a large text file say, `haystack.txt` and an array of tokens say, `['India', 'January', 'gold', 'Mr So-and-So']`. My aim is to search the file with the array in the most efficient way. In general, number of words in `haystack.txt` will be at least 20-50 times the number of tokens in the array.  The search should return `true` when at least one string in the array is found in the file.

I was thinking of generating tokens from `haystack.txt` and creating a `trie` out of it. Then, use the array of strings to be searched as an input to search the `trie`.

What are your suggestions?

**Comment by Hugo-ter-Doest** [comment]
Much simpler, you can use `str.includes(str1)` for each token in your array.
