### ISSUE TITLE
invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by wimkumpen** [NaturalNode/natural#546]
Version: natural@2.1.5
Browser: Safari 13
File: natural/lib/natural/tokenizers/sentence_tokenizer.js
Line: 35

`var tokens = text.match(/(?<=\s+|^)[\"\'\‘\“\'\"\[\(\{\⟨](.*?[.?!])(\s[.?!])*[\"\'\’\”\'\"\]\)\}\⟩](?=\s+|$)|(?<=\s+|^)\S(.*?[.?!])(\s[.?!])*(?=\s+|$)/g);`

Bug in console: invalid regular expression: invalid group specifier name.

I only got this on iOS and with a safari browser.

**Comment by Hugo-ter-Doest** [comment]
I did some research into refactoring/replacing the look back and look ahead constructs with something else. But that is not trivial. Any ideas?

**Comment by Hugo-ter-Doest** [comment]
Added a sentence tokenizer based on PEGjs.
