### ISSUE TITLE
webpack in deps

### ISSUE THREAD

**Issue by janakg** [NaturalNode/natural#551]
Hi, Thanks for this lib. Any specific reason for the webpack in the direct dependencies?

**Comment by bigeasy** [comment]
It generates a lot of deprecation warnings and the tests pass when it is removed from the dependencies.

**Comment by Hugo-ter-Doest** [comment]
I think it should  be a development dependences. It is used for testing the use in browsers.

**Comment by Hugo-ter-Doest** [comment]
Moved it to development dependencies.
