### ISSUE TITLE
Sentence Tokenizer Regex Breaks on IOS Safari

### ISSUE THREAD

**Issue by ariel-frischer** [NaturalNode/natural#552]
As of now if you check: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#assertions you can see `lookbehind assertions ((?<= ) and (?<! ))` are not supported on IOS Safari. This actually crashes my entire ReactJS application with this one error message: 
![image](https://user-images.githubusercontent.com/19893395/96358145-cc25fa80-10b8-11eb-8e38-29b2f3cd569e.png)
Looking into my compiled script I found the only lookbehind assertion was:
`s.inherits(i,n),i.prototype.tokenize=function(e){var t=e.match(/(?<=\s+|^)`
Is there a way to re-write this regex? Or use another conditional perhaps without regex.

The regex seems to be inside the [sentence tokenizer](https://github.com/NaturalNode/natural/blob/5149255b18012d7756cf747f3bbc1d68b7a7891e/lib/natural/tokenizers/sentence_tokenizer.js#L35).

**Comment by ariel-frischer** [comment]
#https://github.com/NaturalNode/natural/issues/546

**Comment by edshen17** [comment]
I have the same issue. Any workarounds?

**Comment by ariel-frischer** [comment]
I just forked it and commented it out for now :/  that regex seems difficult to copy without lookbehind assertions. I wasn't using that function anyway.

**Comment by edshen17** [comment]
Thank you so much! My code works on Safari again! I wouldn't have thought of commenting it out. I guess I still have a lot to learn as a programmer, haha.

**Comment by Hugo-ter-Doest** [comment]
I did some research into refactoring/replacing the look back and look ahead constructs with something else. But that is not trivial. Any ideas?

**Comment by Hugo-ter-Doest** [comment]
This issue about compatibility with Safari and issues #449 and #550 made me think about another direction for solving this. Also because I could hardly read and process the regular expression with lookbehinds and lookaheads. I though a more careful and elaborate solution based on parsing was needed. So I build a PEGJS grammar and generated a sentence parser. Pull request is here https://github.com/NaturalNode/natural/pull/558

**Comment by Hugo-ter-Doest** [comment]
You can use the new sentence tokenizer based on pegjs grammar.
