### ISSUE TITLE
New stemming algorithm for french: Carry

### ISSUE THREAD

**Issue by Poyoman39** [NaturalNode/natural#555]
Hi guys and girls !

I implemented on my side the Carry algorithm ( https://fr.wikipedia.org/wiki/Racinisation#Carry.2C_un_algorithme_de_racinisation_pour_le_fran.C3.A7ais )

My work is available here : https://www.npmjs.com/package/node-carry

It's a stemming algorithm specialized with french words.

Feel free to include my work inside natural if you think it would be interesting

**Comment by Hugo-ter-Doest** [comment]
Thanks for your contribution! 

I looked at your stemmer, and wrote some tests. I found that it does not stem in the same way as the Porter stemmer aready included in NaturalNode. You can find the Jasmin tests and results in this gist:

https://gist.github.com/Hugo-ter-Doest/edcba0c17fae1e5fdee4409ab2044e7f

Is your stemmer working like it is meant to? Did you know that it works differently from the Porter stemmer?

Could you please have a look at it?

**Comment by Poyoman39** [comment]
Hi @Hugo-ter-Doest thank you for your answer,

Effectively this stemmer is intended to give better results than the Porter one for french words. (that's what the carry project searchers say). So indeed it's not meant to give the same results.

Authors of the algorythm describe the differences of results in their article http://www.otlet-institute.org/docs/Carry.pdf (written in french)

At first i implemented the algorithm described in their PDF, but it had kind of weird weakness. So I contacted the authors of the projects, they gave me access to the official C implementation of the algorithm, so i can implement it well :)

**Comment by Hugo-ter-Doest** [comment]
I will integrate your stemmer soon.

**Comment by Poyoman39** [comment]
Nice ! 😊 if ever you have any questions about my implementation. I will provide help !

**Comment by Hugo-ter-Doest** [comment]
First integration is ready, see https://github.com/NaturalNode/natural/pull/557

**Comment by Poyoman39** [comment]
A huge thank for your integration ! I'm really to have participated to this project with your help ! :) Your changes look fine to me.

**Comment by Hugo-ter-Doest** [comment]
Done
