### ISSUE TITLE
Levenshtein distance typing

### ISSUE THREAD

**Issue by torava** [NaturalNode/natural#556]
Hi. `natural.LevenshteinDistance(source, target, {search: true})` will return number type although it's not. Therefore it cannot be used with TypeScript.

**Comment by Hugo-ter-Doest** [comment]
It should return a number indeed. What do you mean? Please show some code and the error output.

**Comment by Hugo-ter-Doest** [comment]
I think it's better to create a separate method that includes search. Now the return type is not consistent. Something like `LevenshteinDistanceWithSearch`

**Comment by Hugo-ter-Doest** [comment]
Solved in #594. 

This is a major change. Will tag a new release soon.
