### ISSUE TITLE
Got Uncaught SyntaxError when trying to use WordPunctTokenizer in Chrome Extension

### ISSUE THREAD

**Issue by sergeyt** [NaturalNode/natural#566]
I got the following error:

```Uncaught SyntaxError: Invalid regular expression: /([A-zÃ€-Ã¿-]+|[0-9._]+|.|!|\?|'|"|:|;|,|-)/: Range out of order in character class```

**Comment by Hugo-ter-Doest** [comment]
I do not recognize the regular expression from the code:
```
const WordPunctTokenizer = function (options) {
  this._pattern = /([A-Za-zÀ-ÿ-]+|[0-9._]+|.|!|\?|'|"|:|;|,|-)/i
  RegexpTokenizer.call(this, options)
}
```
Difficult to see what is going on. Closing the issue now. If you have additional information on the context please reopen the issue.
