### ISSUE TITLE
Error in MacOS Safari

### ISSUE THREAD

**Issue by ashwinnaidu** [NaturalNode/natural#574]
Getting the following error in safari. Is there a fix for this ?
SyntaxError: Invalid regular expression: invalid group specifier name

<img width="1087" alt="Screenshot 2021-02-01 at 7 11 15 PM" src="https://user-images.githubusercontent.com/13837124/106466451-56a43580-64c1-11eb-8bf4-1d8290a5adb3.png">

**Comment by Hugo-ter-Doest** [comment]
duplicate with #552

As an alternative you can use the sentence tokenizer based on pegjs.
