### ISSUE TITLE
Upgrade type definitions for @types/natural

### ISSUE THREAD

**Issue by marcoklein** [NaturalNode/natural#577]
I see that the type definitions at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/natural/index.d.ts are for version 2.1.

Are there plans on upgrading them to 3.0.1?

For example I am unable to import the HammingDistance with this version mismatch:

```json
  "dependencies": {
    "natural": "^3.0.1"
  },
  "devDependencies": {
    "@types/natural": "^2.1.1"
  }
```

**Comment by Hugo-ter-Doest** [comment]
I was not aware of this typescript version of natural's interface. I think you should ask the authors of that file.

**Comment by Brian-McBride** [comment]
The way @types works is that pretty much anyone can create PRs there. 

Ideally, however, this repo should grab that index.d.ts and drop it into this project and update the types here. 
Basically, please support typescript :)

**Comment by Hugo-ter-Doest** [comment]
TypeScript type definitions are now part of natural. See #659
