### ISSUE TITLE
StemmerJa bug `this` is not defined

### ISSUE THREAD

**Issue by niftylettuce** [NaturalNode/natural#586]
Related to #584, and possibly affects all other stemmers, on v4.0.0.

```sh
> const stem = natural.StemmerJa.stem;
undefined
> stem('foo')
Uncaught TypeError: Cannot read property 'stemKatakana' of undefined
    at StemmerJa.stem (/Users/user/Projects/spamscanner/node_modules/natural/lib/natural/stemmers/stemmer_ja.js:85:16)
> natural.StemmerJa.stem('foo')
'foo'
> const stem2 = natural.StemmerJa.stem.bind(natural.StemmerJa);
undefined
> stem2('foo')
'foo'
```

It would be nice it if bound scope automatically for `this`.

**Comment by Hugo-ter-Doest** [comment]
This is not how it should be used. The stemmer is a class that is instantiated into an object and you call methods of that object. So, you cannot pick functions from the object and call them out of context. Of course, then you get problems with `this`. Binding it afterwards is not the way to go.
