### ISSUE TITLE
Pug security error

### ISSUE THREAD

**Issue by SubJunk** [NaturalNode/natural#588]
There is a security problem in versions of Pug below 3.0.1, would you please bump it here?

![image](https://user-images.githubusercontent.com/584228/110256688-0f98eb00-7fff-11eb-9f9a-78b70fbd7276.png)

The vulnerability issue is https://github.com/pugjs/pug/issues/3312

**Comment by Hugo-ter-Doest** [comment]
I removed the jscpd dependency from `package.json`. See #590. That was unnecessary anyway. I think that will solve the problem.

**Comment by SubJunk** [comment]
Thanks!
