### ISSUE TITLE
NGrams doesnt support text with accent

### ISSUE THREAD

**Issue by sam68740** [NaturalNode/natural#600]
Texts with accents (such as French) are not processed properly by the ngram function.

For instance, if you run this: 

`NGrams.ngrams("Nous avons sélectionné avec des professeurs expérimentés de français des textes faciles à lire et amusants", 2))`

Here the output

[ 'Nous', 'avons' ],
[ 'avons', 's' ],
**[ 's', 'lectionn' ],**
**[ 'lectionn', 'avec' ],**
[ 'avec', 'des' ],
[ 'des', 'professeurs' ],
**[ 'professeurs', 'exp' ],**
**[ 'exp', 'riment' ],**
**[ 'riment', 's' ],**
[ 's', 'de' ],
[ 'de', 'fran' ],
 [ 'fran', 'ais' ],
[ 'ais', 'des' ],
[ 'des', 'textes' ],
[ 'textes', 'faciles' ],
[ 'faciles', 'lire' ],
[ 'lire', 'et' ],
[ 'et', 'amusants' ]

As you can see the accents are removed and split one word into 2 or 3 parts.

**Comment by Hugo-ter-Doest** [comment]
I see what happens. The standard tokenizer of the NGrams module is the WordTokenizer. It tokenizes english, not french (with accents). You can set the right tokenizer for your language like this:

```
const Tokenizer = natural.AggressiveTokenizerFr
const tokenizer = new Tokenizer()
NGrams.setTokenizer(tokenizer)
```

And then try agai your sentence. Result will be:
```
[
  [ 'Nous', 'avons' ],
  [ 'avons', 'sélectionné' ],
  [ 'sélectionné', 'avec' ],
  [ 'avec', 'des' ],
  [ 'des', 'professeurs' ],
  [ 'professeurs', 'expérimentés' ],
  [ 'expérimentés', 'de' ],
  [ 'de', 'français' ],
  [ 'français', 'des' ],
  [ 'des', 'textes' ],
  [ 'textes', 'faciles' ],
  [ 'faciles', 'à' ],
  [ 'à', 'lire' ],
  [ 'lire', 'et' ],
  [ 'et', 'amusants' ]
]
```
