### ISSUE TITLE
natural.DiceCoefficient does not compute the Dice coefficient

### ISSUE THREAD

**Issue by vibl** [NaturalNode/natural#603]
Your algorithm count all bigram duplicates, whereas the Dice coefficient only count distinct bigrams.

Please have a look at Talisman, NLTK or the algorithms in many languages in https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Dice%27s_coefficient for a proper implementation.

As an example, when comparing two Wikipedia articles with a Dice coefficient of 0.76, your algorithm outputs 0.42 (The two articles are the raw wikitext of https://en.wikipedia.org/wiki/French_Revolution and https://en.wikipedia.org/wiki/Influence_of_the_French_Revolution, you have to click on the Edit tab to get the wikitext).

**Comment by Hugo-ter-Doest** [comment]
Thanks for your feedback. I created a new version of the Dice coefficient module based on the algorithms site you mentioned. I added support for strings of length 1 and made it case insensitive. Like in the original version.
