### ISSUE TITLE
Potential memory leak due to brill_pos_tagger

### ISSUE THREAD

**Issue by niftylettuce** [NaturalNode/natural#607]
<img width="1305" alt="Screen Shot 2021-08-21 at 5 49 10 PM" src="https://user-images.githubusercontent.com/523141/130336667-7d1048e3-a31d-4183-b5ad-c6c65e54cf10.png">

Consistently this takes up 12%+ of memory - hoping you have an idea how I can alleviate this

<img width="1305" alt="Screen Shot 2021-08-21 at 6 02 24 PM" src="https://user-images.githubusercontent.com/523141/130336885-e91a0d2b-fec0-4323-8c0f-b631d363eec9.png">

My usage is at https://github.com/spamscanner/spamscanner/blob/master/index.js

**Comment by Hugo-ter-Doest** [comment]
I think the lexicon takes up quite some memory. I don't think it is a memory leak.
