### ISSUE TITLE
NGrams doesnt support words with hyphen

### ISSUE THREAD

**Issue by sam68740** [NaturalNode/natural#609]
There are some words in French (and maybe other languages) that contain a hyphen.
Example:
- sous-bois
- sous-pages

It would be great if Natural could manage these cases.

Here the current output
 
let res = NGrams.ngrams("Des sous-pages dans le sous-bois de la ville de Paris.", 2)
[["Des","sous"],["sous","pages"],["pages","dans"],["dans","le"],["le","sous"],["sous","bois"],["bois","de"],["de","la"],["la","ville"],["ville","de"],["de","Paris"]]

**Comment by Hugo-ter-Doest** [comment]
Solved with https://github.com/NaturalNode/natural/pull/610
