### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by hyandell** [NaturalNode/natural#611]
Hi natural folk :)

I noticed that, while the project itself is licensed MIT and calls out the WordNet license, a bunch of the files are under GPL-3.0.

* lib/natural/classifiers/maxent/**
* lib/natural/brill_pos_tagger/lib/**

Is this intended?

**Comment by Hugo-ter-Doest** [comment]
Correct, the overall license is MIT. The Wordnet license is because of the integration with Wordnet. The GPL on Maxent and Brill tagger is a mistake; I will fix these.

**Comment by hyandell** [comment]
Thank you Hugo :)

**Comment by Hugo-ter-Doest** [comment]
Fixed in #612
