### ISSUE TITLE
Is `wordnet.lookup` an `async` function? 

### ISSUE THREAD

**Issue by fetahokey** [NaturalNode/natural#628]
## Trying to build an array of synonyms for each word in an `Array `with `wordnet `and `natural`
![code](https://user-images.githubusercontent.com/32603079/143028659-7dba4aa2-97cf-4b78-9167-37636864cc19.png)

## code
```
const wordnet = new natural.WordNet();
const setSyns: any = {};
const handleLookup = (word: string, syns: string[]) => {
  setSyns[word] = syns;
};
wordnet.lookup("word", (x) => {
  const synsList = _.flatMapDeep(x, (y) => y.synonyms);
  handleLookup("word", _.uniq(synsList));
});
console.log(setSyns);

```

## issue
 - every time I get an empty array  
    ` // { }
    `
## expectation
I want to wait for the lookup function, to feel all the possible SynSet's, before proceeding next step,
similar Qst [1](https://stackoverflow.com/questions/53722013/get-array-of-synonyms-from-natural-nodess-wordnet-nodejs)

**Comment by Hugo-ter-Doest** [comment]
Yes, de lookup function takes a callback. The console.log in your code is called immediately, therefore it is still empty when it is printed..
