### ISSUE TITLE
Is there a way to filter out stopwords without stemming?

### ISSUE THREAD

**Issue by amywoon** [NaturalNode/natural#629]
I know that tokenizeAndStem() is able to stem and filter out the stopwords, but I don't want the stemming.
I just want to filter out the stopwords.

I tried importing words directly from the file like so:
import words from 'natural/lib/natural/util/stopwords';

but I want to know if there is another way. Thanks!

**Comment by Hugo-ter-Doest** [comment]
Currently it is not possible to filter stopwords from a text with natural. You can import the list, tokenize the text, and use the list to filter out the stop words.
