### ISSUE TITLE
Any supported material on browserify compatibility for V8/client-side use?

### ISSUE THREAD

**Issue by douglas444** [NaturalNode/natural#630]
I want to use natural from V8 so I'm looking for a way to apply browserify on it in order to get a single js file that does not require disk access. I think it's analogous to obtaining a client-side version. Is there some sort of official support to it? What I need is to convert it to pure JS (using browserify) and test everything. I would repeat this process every time I want to get the most recent version of natural.

Is there any official step-by-step, tests and maybe a list of compatible modules? Or maybe an official one single file "build"?

**Comment by Hugo-ter-Doest** [comment]
There is support for webpack: see https://github.com/NaturalNode/natural/blob/5.1.13/gulpfile.js
