### ISSUE TITLE
Classification Error

### ISSUE THREAD

**Issue by WillKenzie** [NaturalNode/natural#643]
So, I have a JSON file with about 8,000 items in it, all categorized by a number. I noticed that the biggest number, as well as the last number loaded into Natural, would be selected abnormally. So, I created a fallback intent and called it "6". This fallback intent is triggered even when I copy-paste from the JSON, even though the item isn't in that intent. What is going on? Is this an error with my dataset, or an error with Natural? Below is the code I use to load my JSON into Natural's document format.

```
const natural = require('natural')
const classifier = new natural.BayesClassifier()
const model = require("./model.json")

for (key of Object.keys(model)) {
    for (string of model[key]) {
        classifier.addDocument(string, key)
    }
}
```

If you need any more information, please just ask!

**Comment by Hugo-ter-Doest** [comment]
I do not understand what is going wrong? What do you mean by 'This fallback intent is triggered even when I copy-paste from the JSON, even though the item isn't in that intent.' Please share some data, so that I can see the structure.
