### ISSUE TITLE
Add official TypeScript types?

### ISSUE THREAD

**Issue by justinfagnani** [NaturalNode/natural#655]
Types on DefinitelyTyped can easily be wrong or get stale, as shown by a few issues here that are really about the DefinitelyTyped package. Could this project publish official, up-to-date typings? If would help in using the APIs tremendously.

**Comment by andynunes** [comment]
Agreed, this would greatly aid in integrating cleanly with TypeScript projects.

**Comment by Hugo-ter-Doest** [comment]
@andynunes @justinfagnani 
I am in the process of adding TypeScript support. Would be great if could take a look at the first steps. I added a `index.d.ts` to the tokenizers folder to begin with. See https://github.com/NaturalNode/natural/pull/659

My plan is to add TypeScript index files to each folder and then to bring them together in an overall index file at the main level. Just as is done with the Javascript index files. Like this NaturalNode can be used in modules. You don't have to include the complete library.

**Comment by Hugo-ter-Doest** [comment]
Merged #659
