### ISSUE TITLE
Unneeded `tsc` dependency

### ISSUE THREAD

**Issue by kirillgroshkov** [NaturalNode/natural#664]
package.json has a dependency on [tsc](https://www.npmjs.com/package/tsc) module, which I assume is a mistake. Probably typescript's `tsc` was assumed, but it is instead provided by a `typescript` dependency.

Suggestion is to remove `tsc` dependency from package.json.

I can create a PR if I get a 👍

**Comment by Hugo-ter-Doest** [comment]
I think it appeared there because I added TypeScript types to the library. It should be a develop dependency. Would be great if you create a PR!

**Comment by kirillgroshkov** [comment]
To clarify - it should **not** be a devDep neither. `tsc` bin is provided by `typescript` dependency already.

**Comment by Hugo-ter-Doest** [comment]
Ok thanks for your explanation

**Comment by kirillgroshkov** [comment]
@Hugo-ter-Doest I've created a PR, please review
