### ISSUE TITLE
 SentenceTokenizer works badly with numbered lists

### ISSUE THREAD

**Issue by painkkiller** [NaturalNode/natural#678]
`SentenceTokenizer` works badly with numbered lists. For example this text will produce 10 sentences:
```
1.  Where is the bar located? 
2.  What are the bar's opening hours? 
3. Is there an entrance fee in the bar? 
4. What styles of music are typically played in the bar? 
5. Does the bar offer any discounts for students?
```

**Comment by Hugo-ter-Doest** [comment]
Yes, the sentence tokenizer looks at the syntax of a text based on puncuation and cannot distinguish between a period used for a numbered and a period used the end a sentence. Another more advanced mechanism would be needed to parse numbered list as well as ordinary sentences ending in a period. Won't fix, that is not in this parser built on regular expressions.
