### ISSUE TITLE
Release updated type declarations

### ISSUE THREAD

**Issue by rd-dreich** [NaturalNode/natural#683]
The type declarations were updated in #670. However, this update is not included in the latest release ([6.2.0](https://github.com/NaturalNode/natural/releases/tag/6.2.0)) leading to errors during compilation. The "fix" currently is to either cast it to `any` or ignore type definitions during compilation.
Is there a release planned for the near future including this update?
Thanks :-)

**Comment by Hugo-ter-Doest** [comment]
Published a new release to NPM!
