### ISSUE TITLE
Sanity check - client side only possible?

### ISSUE THREAD

**Issue by johntiger1** [NaturalNode/natural#688]
Is it possible to use this library purely from the client? i.e. in your index.html, have something like:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GPT-4 Conversation Visualization</title>
    <script src="https://d3js.org/d3.v6.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wordcloud2.js/1.1.0/wordcloud2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/natural/1.2.0/natural.min.js"></script>
</head>
```

**Comment by johntiger1** [comment]
This is what GPT4 is saying:
"Node.js packages are built around the CommonJS module system, which relies on the require() function to import modules. This is not natively supported in browsers, which use the ECMAScript (ES) module system with import and export statements."

**Comment by Hugo-ter-Doest** [comment]
Yes, you can use webpack to use Natural client side. See the `webpack.config.js` that is in the root of the repo. It may well be a good starting point. I use the webpack configuration for testing in the browser using `jasmineBrowser`.
