### ISSUE TITLE
Error when using natural from deno using esm.sh

### ISSUE THREAD

**Issue by whaaaley** [NaturalNode/natural#691]
```
error: The module's source code could not be parsed: `await` cannot be used as an identifier in an async context at https://esm.sh/v127/afinn-165@1.0.4/denonext/afinn-165.development.mjs:3650:5
```

If we go to that file we can see this:
![image](https://github.com/NaturalNode/natural/assets/7419947/e62194a8-3c38-4be7-8b73-b55e10c22e45)

This is preventing me from using natural in Deno Deploy atm. Is this a natural issue or an esm.sh issue?

https://github.com/esm-dev/esm.sh/issues/674

**Comment by Hugo-ter-Doest** [comment]
Natural does not support ESM.
