### ISSUE TITLE
Enhancement: Stricter Typing for tag Field in BrillPOSTaggedWord Interface

### ISSUE THREAD

**Issue by natashaannn** [NaturalNode/natural#692]
**Description:**
I would like to request an enhancement to the Natural NPM library regarding the definition of the tag field in the `BrillPOSTaggedWord` interface. Currently, the tag field is of type string, which is quite generic and allows any string value. However, it would be beneficial to have a stricter type definition that specifically accounts for all the possible Part-of-Speech (POS) tags.

**Proposed Solution:**
To address this, I suggest introducing a more specific type for the tag field by defining an explicit union type that includes all the valid POS tags. This would provide improved type safety and make it easier for developers to work with the library.

I have already created a sample type called POSTags with all the relevant POS tags defined as string literals. Here is an example:
```
/**
 * Represents Part-of-Speech (POS) tags.
* @typedef {'NN'   // Noun, singular or mass
 *           | 'VB'   // Verb, base form
 *           | 'JJ'   // Adjective
 *           | 'RB'   // Adverb
 *           | 'DT'   // Determiner
 *           | 'IN'   // Preposition or subordinating conjunction
 * ...
 */
type POSTags =
  | 'NN'
  | 'VB'
  | 'JJ'
  | 'RB'
  // ... (list continues with all valid POS tags)
  | 'BES'
  | 'HVS';

interface BrillPOSTaggedWord {
  token: string;
  tag: POSTags;
}
```

This enhancement would ensure that the tag field only accepts values that match the defined POS tags, reducing the risk of errors and improving the developer experience.

**Impact and Benefits:**

- **Improved Type Safety:** With stricter typing, developers can catch potential errors related to incorrect or misspelled POS tags at compile-time rather than at runtime.
- **Enhanced Developer Experience:** Clear and specific types provide better code understanding, enabling developers to work more confidently and efficiently with the Natural library.
- **Facilitated Integration:** A well-defined type for the tag field simplifies the integration of Natural into TypeScript projects, as the expected types become more explicit.

**Additional Context :**
I believe that enforcing a more specific type for the tag field would be a valuable enhancement to the Natural library, especially for projects that utilize TypeScript and require stronger typing. It would align with the library's goal of providing reliable and efficient NLP functionalities.

I am willing to contribute to this enhancement by providing a pull request with the proposed changes, if it aligns with the project maintainers' vision.

Thank you for considering this enhancement request. I look forward to your feedback and discussing further improvements!

**Comment by Hugo-ter-Doest** [comment]
For starters, a great idea to offer more strict typing for tags, However, the set of tags is not static. It varies with the set of transformation rules that is loaded.
