### ISSUE TITLE
natural.AggressiveTokenizerRu() doesn't filter out non-cyrillic characters 

### ISSUE THREAD

**Issue by hellopavelzinoviev** [NaturalNode/natural#697]
Hey guys!

I played around with "natural" and found out that this `.AggressiveTokenizerRu()` is not really "aggressive" :) As far as I understand the docs, it should filter out all non-Cyrillic characters. But this is not the case.

I see that the regular expression rule contains Latin characters — `/[^a-za-ue0-9]/gi`. Is this how it supposed to be?

https://github.com/NaturalNode/natural/blob/3a14c693f4e9d0c1e0868e71302a75dce01022dd/lib/natural/tokenizers/aggressive_tokenizer_ru.js#L41

**Comment by Hugo-ter-Doest** [comment]
Well, that is not how the tokenizer works: anything that uis not alphanumeric or cyrillic is replaced with a space. So space, tabs and punctuation are replaced with space. This is done in function `clearText`, then in function `tokenize` the string is split into tokens based on spaces. The fact that alpanumeric characters are allowed in `clearText` prevents them from being transformed to spaces.
