### ISSUE TITLE
Load model with BayesClassifier and PorterStemmerEs

### ISSUE THREAD

**Issue by pacorecomiendapp** [NaturalNode/natural#720]
I have some problems loading a model with the BayesClassifier using the PorterStemmerEs:

`natural.BayesClassifier.load('classifier.json', natural.PorterStemmerEs, function (err, classifier) {
`

I think I solved it by modifying the source file `/lib/natural/classifiers/bayes_classifier.js`.  This is the new code (line 46):

```
static load (filename, stemmer, callback) {
    Classifier.load(filename, function (err, classifier) {
      if (err) {
        return callback(err)
      } else {
        callback(err, BayesClassifier.restore(classifier, stemmer))
      }
    })
  }
```

Is that ok?

**Comment by yahyaobeid** [comment]
I am having the same problem. You should introduce this as a pull request so they can implement it into the source code.

**Comment by Hugo-ter-Doest** [comment]
Thanks for your PR https://github.com/NaturalNode/natural/pull/724
