### ISSUE TITLE
Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by Areshkew** [NaturalNode/natural#723]
I'm trying to use LogisticRegressionClassifier.

When I call events it says error:
LogisticRegressionClassifier

Code:
`var natural = require('natural');
const PorterStemmerEs = require('natural/lib/natural/stemmers/porter_stemmer_es');
var classifier = new natural.LogisticRegressionClassifier(PorterStemmerEs);

classifier.addDocument('ranchero golpe', 'Huevos');
classifier.addDocument('bbq', 'Huevos');
classifier.addDocument('salchichas ranchero', 'Tortas');

classifier.train();
classifier.events.on('trainedWithDocument', (v) => console.log(v))

classifier.save('classifier.json', (err) => console.log(err))`

**Comment by bent10** [comment]
The error lies within the type definitions. Instead of `classifier.events.on`, it should be `classifier.on`.

**Comment by Hugo-ter-Doest** [comment]
And you need to declare the event listener before you call train:
```
classifier.on('trainedWithDocument', (v) => console.log(v))
classifier.on('doneTraining', (v) => console.log(v))
classifier.train();
```

**Comment by Hugo-ter-Doest** [comment]
Btw discovered some legacy code in the `train` method of the LogisticRegressionClassifier: 
```
Classifier.prototype.train.call(this)
```
I will replace that with an call to `super.train()`
