### ISSUE TITLE
AggressiveTokenizerUk doesn't exist.

### ISSUE THREAD

**Issue by TasseDeCafe** [NaturalNode/natural#734]
AggressiveTokenizerUk doesn't exist. It is mentioned in the docs [here](https://naturalnode.github.io/natural/Tokenizers.html), but it can't be imported. All the other tokenizers in that list can be imported.

**Comment by Hugo-ter-Doest** [comment]
Well, it exists but is not yet exposed in the `index.js`. I will take care of that.
