### ISSUE TITLE
Logistic Regression Classifier's load function incorrectly passing callback as stemmer

### ISSUE THREAD

**Issue by ThomasKirst** [NaturalNode/natural#742]
Hello,

I've encountered an issue with the `load` function in the `LogisticRegressionClassifier` class. It appears that the model is not being loaded correctly when this function is called.

Here's the relevant code from 
[`logistic_regression_classifier.js`](https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/logistic_regression_classifier.js#L45):

```javascript
static load (filename, stemmer, callback) {
    // The second argument `stemmer` is missing
    Classifier.load(filename, (err, classifier) => {
      if (err) {
        callback(err)
      } else {
        callback(err, LogisticRegressionClassifier.restore(classifier, stemmer))
      }
    })
  }
```

In this code, `stemmer` is not passed along, and the callback function is being passed as the second argument to `Classifier.load`, which expects a stemmer as the second argument.

In contrast, the load function in the [`BayesClassifier`](https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/bayes_classifier.js#L46C1-L54C4) class seems to work as expected:

```javascript
 static load (filename, stemmer, callback) {
    // The 2nd argument `stemmer` is present
    Classifier.load(filename, stemmer, function (err, classifier) {
      if (err) {
        return callback(err)
      } else {
        callback(err, BayesClassifier.restore(classifier, stemmer))
      }
    })
  }
```

The signature of the load function in the base class [`Classifier`](https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/classifier.js#L157C3-L169C4) does expect the `stemmer` as the second argument:

```javascript
  static load (filename, stemmer, callback) {
    if (!callback) {
      return
    }
    fs.readFile(filename, 'utf8', function (err, data) {
      if (err) {
        callback(err, null)
      } else {
        const classifier = JSON.parse(data)
        callback(err, Classifier.restore(classifier, stemmer))
      }
    })
  }
```

When I call the `load` function on the `LogisticRegressionClassifier`, it does not load the model as expected. This issue does not occur with the `BayesClassifier`.

Here's a patch that adds the missing `stemmer` argument in `logistic_regression_classifier.js`:

```diff
  static load (filename, stemmer, callback) {
-    Classifier.load(filename, (err, classifier) => {
+    Classifier.load(filename, stemmer, (err, classifier) => {
      if (err) {
        callback(err)
      } else {
        callback(err, LogisticRegressionClassifier.restore(classifier, stemmer))
      }
    })
  }
```

With this change, the `stemmer` argument is correctly passed to the `Classifier.load` method.

I'm not entirely sure about the potential implications this change could have on other parts of the codebase. It would be great if you could review this change and consider it for the next release.

Thank you!
– Thomas

**Comment by Hugo-ter-Doest** [comment]
Good catch! Repaired it in #743 and merged it.
I will publish a new release tomorrow.
