### ISSUE TITLE
Phonetics not work

### ISSUE THREAD

**Issue by a-sekmani** [NaturalNode/natural#746]
**Describe the bug**
Hello, I am a computer science student and I am still somewhat new to programming, but I downloaded the library within one of my projects, Then I tried to use the Phonetics feature according to the code included in the explanation, But it does not work at all, I am requesting some methods such as:

`metaphone.compare(wordA, wordB)`

But I get problem "TypeError: metaphone.compare is not a function"

Although I have so far only copied the code included in the explanation

`var natural = require('natural');
var metaphone = natural.Metaphone;
var soundEx = natural.SoundEx;

var wordA = 'phonetics';
var wordB = 'fonetix';

if(metaphone.compare(wordA, wordB))
    console.log('they sound alike!');`

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Webstorm 2024.1.3
 - Node 22.2.0

**Comment by Hugo-ter-Doest** [comment]
I am sorry, the documentation is wrong. Metaphone is a class. So you should create an instance like this:
```
var metaphone = new natural.Metaphone()
```
The same holds for `SoundEx`.

**Comment by Hugo-ter-Doest** [comment]
I updated the documentation at https://naturalnode.github.io/natural/phonetics.html
