### ISSUE TITLE
throw error in some case in SentenceTokenizerNew

### ISSUE THREAD

**Issue by himself65** [NaturalNode/natural#750]
**Describe the bug**

```shell
[peg$SyntaxError: Expected [^ \t\n\r!?([}"`)\]}"`0-9@] but end of input found.
] {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: true,
      ignoreCase: false
    }
  ],
  found: null,
  location: {
    start: { offset: 183, line: 1, column: 184 },
    end: { offset: 183, line: 1, column: 184 }
  }
}
```

```js
const SentenceTokenizerNew = require("natural").SentenceTokenizerNew
const t = new SentenceTokenizerNew()
t.tokenize("A card must be of uniform thickness and made of unfolded and uncreased paper or cardstock of approximately the quality and weight of a stamped card (i.e., a card available from USPS).")
```

**To Reproduce**
Steps to reproduce the behavior, or clear and concise code excerpts that trigger the unexpected behaviour.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
related to https://github.com/run-llama/LlamaIndexTS/pull/1087

**Comment by Hugo-ter-Doest** [comment]
I think this sentence tokenizer based on pegjs is never going to work as expected because of the strict nature of such a parser. Your better option is the sentence tokenizer `SentenceTokenizer` based on regular expressions.

**Comment by Hugo-ter-Doest** [comment]
I removed the grammar-based sentence tokenizer. And rewrote the original sentence tokenizer into a more capable tokenizer that can handle abbreviations, URI's, etc.
