### ISSUE TITLE
SentenceTokenizer breaks if you do not pass abbreviations

### ISSUE THREAD

**Issue by Safrone** [NaturalNode/natural#752]
**Describe the bug**
with the new version 8.0.0 using `SentenceTokenizer` without passing in abbreviations leads to errors on running tokenize

**To Reproduce**
```
import natural from "natural"; 
let transcript = 'test';
const tokenizer = new natural.SentenceTokenizer();
let transcriptSentences = tokenizer.tokenize(transcript);
```
```
TypeError
Cannot read properties of undefined (reading 'map')

Details
    at SentenceTokenizer.replaceAbbreviations (/tmp/node_modules/.pnpm/natural@8.0.0/node_modules/natural/lib/natural/tokenizers/sentence_tokenizer.js:67:55)
    at SentenceTokenizer.tokenize (/tmp/node_modules/.pnpm/natural@8.0.0/node_modules/natural/lib/natural/tokenizers/sentence_tokenizer.js:152:26)
    ...
```

**Expected behavior**
`SentenceTokenizer` should probably handle undefined abbreviations list more gracefully

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser chrome
 - Version 22.04

**Additional context**
probably needs a `if (abbreviations)` [here](https://github.com/NaturalNode/natural/commit/fcb696cae1a4be5fda64d8c8f94225eed9971af6?diff=split&w=0#diff-ad7918a8ed684f0c5bd9fc15cf5688db1a1626ea4f1cedaa42d71f4b49caaadbR44)

**Comment by Hugo-ter-Doest** [comment]
Fixed in #753
