### ISSUE TITLE
What 了 happened?

### ISSUE THREAD

**Issue by iibrat** [NaturalNode/natural#755]
`const tokenizer = new natural.TreebankWordTokenizer()
 return tokenizer.tokenize(text)`

I'm gonna study for the test. 

['I', "'m", 'gon', 'na', 'study', 'for', 'the', 'test', '.']

I'm  => "I" "m" ??
gonna => "gon" "na" ??

**Comment by Hugo-ter-Doest** [comment]
The Treebank tokenizer replaces some contractions by the two recognized parts, for instance `I'm` by `I` and `m`. After that you can process it further, for instance assigning PoS tags.
